### ISSUE TITLE
cannot launch on macOS Monterey

### ISSUE THREAD

**Issue by dabing1022** [wulkano/Kap#1019]
**macOS version:**: macOS Monterey 12.0 beta
**Kap version:**: 3.3.2

cannot launch on monterey 12.0 beta, an error image below:

![image](https://user-images.githubusercontent.com/1892303/121278857-0b35e400-c906-11eb-960e-a70a16bb89b6.png)

```javascript
Uncaught Exception:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at macosRelease (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-release/index.js:26:26)
at Object.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/errors.js:54:17)
at Module._compile (internal/modules/cjs/loader.js:968:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
at Module.load (internal/modules/cjs/loader.js:816:32)
at Module._load (internal/modules/cjs/loader.js:728:14)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Module.require (internal/modules/cjs/loader.js:853:19)
at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by dabing1022** [comment]
OK. I digged the source code 
```javascript
const nameMap = new Map([
	[20, ['Big Sur', '11']],
	[19, ['Catalina', '10.15']],
	[18, ['Mojave', '10.14']],
	[17, ['High Sierra', '10.13']],
	[16, ['Sierra', '10.12']],
	[15, ['El Capitan', '10.11']],
	[14, ['Yosemite', '10.10']],
	[13, ['Mavericks', '10.9']],
	[12, ['Mountain Lion', '10.8']],
	[11, ['Lion', '10.7']],
	[10, ['Snow Leopard', '10.6']],
	[9, ['Leopard', '10.5']],
	[8, ['Tiger', '10.4']],
	[7, ['Panther', '10.3']],
	[6, ['Jaguar', '10.2']],
	[5, ['Puma', '10.1']]
]);

const macosRelease = release => {
	release = Number((release || os.release()).split('.')[0]);

	const [name, version] = nameMap.get(release);

	return {
		name,
		version
	};
};
```

Because of macos Monterey is Version 12, nameMap.get(release) is null, so nameMap should add 
`[21, ['Monterey', '12']]`

**Comment by dabing1022** [comment]
OK. I digged the source code 
```javascript
const nameMap = new Map([
	[20, ['Big Sur', '11']],
	[19, ['Catalina', '10.15']],
	[18, ['Mojave', '10.14']],
	[17, ['High Sierra', '10.13']],
	[16, ['Sierra', '10.12']],
	[15, ['El Capitan', '10.11']],
	[14, ['Yosemite', '10.10']],
	[13, ['Mavericks', '10.9']],
	[12, ['Mountain Lion', '10.8']],
	[11, ['Lion', '10.7']],
	[10, ['Snow Leopard', '10.6']],
	[9, ['Leopard', '10.5']],
	[8, ['Tiger', '10.4']],
	[7, ['Panther', '10.3']],
	[6, ['Jaguar', '10.2']],
	[5, ['Puma', '10.1']]
]);

const macosRelease = release => {
	release = Number((release || os.release()).split('.')[0]);

	const [name, version] = nameMap.get(release);

	return {
		name,
		version
	};
};
```

Because of macos Monterey is Version 12, nameMap.get(release) is null, so nameMap should add 
`[21, ['Monterey', '12']]`

**Comment by dabing1022** [comment]
we should upgrade node_module: macos-release to 2.5.0

here is the support for Monterey:
https://github.com/sindresorhus/macos-release/commit/d4f2afef4f57afba82fd42a50691a910a82926f2

**Comment by Jokero** [comment]
This is what I get when trying to open Kap downloaded from site on Monterey 12.0.1 (21A559):
![image (17)](https://user-images.githubusercontent.com/434135/148741936-09c50549-23f1-4067-afa4-99d03635b713.png)

Version from brew works.
