### ISSUE TITLE
JavaScript error on macOS@12.0 on startup

### ISSUE THREAD

**Issue by always-maap** [wulkano/Kap#1035]
**macOS version:** 12.0 Beta 21A5304g
**Kap version:** 3.3.2

#### Steps to reproduce 
Install and open. On lunch you will get this error message

```
Uncaught Exception:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at macosRelease (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-release/index.js:26:26)
at Object.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/errors.js:54:17)
at Module._compile (internal/modules/cjs/loader.js:968:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
at Module.load (internal/modules/cjs/loader.js:816:32)
at Module._load (internal/modules/cjs/loader.js:728:14)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Module.require (internal/modules/cjs/loader.js:853:19)
at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by sindresorhus** [comment]
https://github.com/wulkano/Kap/releases/tag/v3.4.0
