### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by oscard0m** [wulkano/Kap#1037]
**Sentry Issue:** [KAP-ARF](https://sentry.io/organizations/wulkano-l0/issues/2655212772/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.4.0

```
Unhandled Promise Rejection

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at downloadWallpaper (/kap-hide-desktop-icons/index.js:88:80)
    at Object.didConfigChange (/kap-hide-desktop-icons/index.js:129:9)
    at PluginConfig.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/plugins/plugin.js:111:172)
    at EventEmitter.onChange (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-store/node_modules/conf/dist/source/index.js:335:26)
    at PluginConfig.set store [as store] (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-store/node_modules/conf/dist/source/index.js:292:21)
    at PluginConfig.clear (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-store/node_modules/conf/dist/source/index.js:233:20)
```

**Comment by jorroll** [comment]
This issue just triggered for me when I disabled the "hide-desktop-icons" plugin. Immediately before disabling this plugin, I had disabled the "key-cast" plugin (which didn't trigger an error).
