### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by isaquepereira** [wulkano/Kap#1042]
**macOS version:**
**Kap version:**

#### Steps to reproduce
Just open the app

#### Current behaviour
Error dialog window

#### Expected behaviour
Open the app clean

#### Workaround
Uncaught Exception:
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
at macosRelease (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-release/index.js:26:26)
at Object.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/errors.js:54:17)
at Module._compile (internal/modules/cjs/loader.js:968:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
at Module.load (internal/modules/cjs/loader.js:816:32)
at Module._load (internal/modules/cjs/loader.js:728:14)
at Module._load (electron/js2c/asar.js:717:26)
at Function.Module._load (electron/js2c/asar.js:717:26)
at Module.require (internal/modules/cjs/loader.js:853:19)
at require (internal/modules/cjs/helpers.js:74:18)

**Comment by codetheweb** [comment]
This was happening to me on a later version as well until I updated to v3.4.1 (latest at time of writing). I believe this has been resolved.

**Comment by saegl5** [comment]
I have v3.4.1 and get the same error message

**Comment by rarestg** [comment]
Got the same issue in the new version -- 3.5.4 for M1 (arm64).

![image](https://user-images.githubusercontent.com/9878259/183779120-4404998e-9b84-4336-aa50-09a6fc346992.png)
