### ISSUE TITLE
Error: ZIP file not provided

### ISSUE THREAD

**Issue by AlecHaring** [wulkano/Kap#1057]
**macOS version:** 11.4
**Kap version:** 3.3.2 (3.3.2.1718)

#### Steps to reproduce
The error came up while Kap was running in the background but it seems to happen if you close Kap completely and then reopen it.

#### Current behaviour
An error message pops up showing this message:
```
Unhandled Promise Rejection
Error: ZIP file not provided: [
  {
    "url": "https://github.com/wulkano/kap/releases/download/v3.5.0/Kap-3.5.0.dmg",
    "info": {
      "url": "Kap-3.5.0.dmg",
      "sha512": "wE6jKbiv+7H75KnMUfLDuuVWJ+L9ujPYdYUFR0wEl0Pbbe/eIgDxe/sTxp8uYC0odSLBH4UkaNiBck4NU77TUA==",
      "size": 122826879
    }
  },
  {
    "url": "https://github.com/wulkano/kap/releases/download/v3.5.0/Kap-3.5.0-arm64.dmg",
    "info": {
      "url": "Kap-3.5.0-arm64.dmg",
      "sha512": "cUF6Lwig2Pl2xC/G3dR1W0uDNrSGqOjrE23K0dND1g10eARrz+OnvyEjiptUv2RUkSxExNjOfa+Ev/OlB4D6XA==",
      "size": 124142614
    }
  }
]
    at newError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/index.js:212:17)
    at MacUpdater.doDownloadUpdate (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:83:48)
    at MacUpdater.downloadUpdate (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:564:19)
    at MacUpdater.doCheckForUpdates (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:524:49)
    at async checkForUpdates (/Applications/Kap.app/Contents/Resources/app.asar/main/index.js:64:7)
```

The `Collect Info and Report` button fails and says `Something went wrong while collecting the information.`

**Comment by sindresorhus** [comment]
https://github.com/wulkano/Kap/releases/tag/v3.5.1
