### ISSUE TITLE
Recording error

### ISSUE THREAD

**Issue by s-seltenreich** [wulkano/Kap#1059]
**Sentry Issue:** [KAP-B8E](https://sentry.io/organizations/wulkano-l0/issues/2849136854/)

**macOS version:**    Monterey (12)
**Kap version:**      3.5.1

```
Recording error

Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
```

**Comment by andreezy777** [comment]
The same problem, 
Looking that the 3.4.2 latest stable release for intel mac

**Comment by filfreire** [comment]
Same issue, `Version 3.5.1 (3.5.1.1783)`
macOS 12.0.1 (21A559), MacBook Pro (16-inch, 2019)

```
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
```

**Comment by cgilroy** [comment]
Same here, `Version 3.5.1 (3.5.1.1783)`
macOS 12.0.1 MacBook Pro (16 inch, 2019)

**Comment by EvHaus** [comment]
Same issue here as well, but what's interested is if I restart my computer then the first recording works, but after that it breaks again.

**Comment by mbukh** [comment]
Same here Monterey 12.0.1 MacBook Pro 16" i9 (2019)

**Comment by CeciliaChiang** [comment]
Same here，Version 3.5.1 (3.5.1.1783) Big Sur 11.5.2 MacBook Pro  (15-inch, 2018)

**Comment by libbyrobinson** [comment]
Same issue, 3.5.1.1783, running MacBook Pro (15-inch, 2019) on Big Sur 11.6. Works first time after restart, then won't record.

**Comment by Serko-Egor** [comment]
Same issue

**Comment by soar** [comment]
The app is totally broken

**Comment by x029a** [comment]
Same, using this often for work. Seeking alternatives now. I've noticed Kap has been running slower and slower anyway. Great app, but seems to have been getting worse.

**Comment by finn-ds** [comment]
following...

**Comment by joergRossdeutscher** [comment]
Might be related to BigSur update. I have the issue since updating yesterday.

**Comment by ITSjwags** [comment]
Also just started seeing this after upgrading to macOS Monterey.

**Comment by mojason-81** [comment]
Haven't ran any updates on my mac lately. Seeing the same issue.  Was working fine just a few days ago.

![image](https://user-images.githubusercontent.com/11481396/146439324-f33219b5-0afb-4b8e-ac93-595d931f8ac8.png)

**Comment by lesliemilitante** [comment]
![image](https://user-images.githubusercontent.com/75963759/146494525-6620f00e-059d-4e06-8403-f57094ec4652.png)
KAP works fine a few days ago then it crashes now.

**Comment by Aaaaash** [comment]
Same problem, on my Intel MAC, KAP can only record once, and the second time will be breaks. 😭
but it worked fine on my M1 MAC 

> Same issue here as well, but what's interested is if I restart my computer then the first recording works, but after that it breaks again.

**Comment by Aaaaash** [comment]
Seems to have something to do with the Electron version update (Electron 12+ and macOS Big Sur)

[child_process spawn locks up renderer for 300 - 3000ms on signed app on macOS Big Sur](https://github.com/electron/electron/issues/26143)

The interim solution was to use version 3.4.2 on Intel Mac
[Download Kap-3.4.2](https://github.com/wulkano/Kap/releases/download/v3.4.2/Kap-3.4.2.dmg)

**Comment by John60676** [comment]
> Seems to have something to do with the Electron version update (Electron 12+ and macOS Big Sur)
> 
> [child_process spawn locks up renderer for 300 - 3000ms on signed app on macOS Big Sur](https://github.com/electron/electron/issues/26143)
> 
> The interim solution was to use version 3.4.2 on Intel Mac [Download Kap-3.4.2](https://github.com/wulkano/Kap/releases/download/v3.4.2/Kap-3.4.2.dmg)

thanks, it work for me.

**Comment by davidcalhoun** [comment]
Having the same issue here with `Kap 3.5.1` running on `macOS 11.6 Big Sur`.  Note that it's temporarily fixed after restarting the system, then seems to work for the first capture but breaks again after that.

Thank you @Aaaaash, [downgrading to 3.4.2](https://github.com/wulkano/Kap/releases/download/v3.4.2/Kap-3.4.2.dmg) is a working workaround for now for me.

**Comment by CeciliaChiang** [comment]
> Seems to have something to do with the Electron version update (Electron 12+ and macOS Big Sur)
> 
> [child_process spawn locks up renderer for 300 - 3000ms on signed app on macOS Big Sur](https://github.com/electron/electron/issues/26143)
> 
> The interim solution was to use version 3.4.2 on Intel Mac [Download Kap-3.4.2](https://github.com/wulkano/Kap/releases/download/v3.4.2/Kap-3.4.2.dmg)

Thanks a lot @Aaaaash , it works😊

**Comment by rajohns08** [comment]
Same issue here on Kap 3.5.1 and macOS 11.6.1 (Intel mac)

**Comment by soar** [comment]
Workaround for Brew users:

```bash
brew uninstall kap
brew tap-new local/homebrew-cask
mkdir "$(brew --repository local/homebrew-cask)/Casks"
wget "https://raw.githubusercontent.com/Homebrew/homebrew-cask/a6998a002502ecdd0c111c99964069dca3bc5df3/Casks/kap.rb" -O "$(brew --repository local/homebrew-cask)/Casks/kap.rb"
brew install local/homebrew-cask/kap
```

**Comment by joergRossdeutscher** [comment]
If I understand this correctly, this is not a fix, but just a downgrade to 3.4.2

(Don't want to critizise that, thanks for the work, just mentioning: Those users who, like me, think this leads to a pre-released fixed beta-something: No, it doesn't. It's just the old package). Please correct me if I'm wrong.

**Comment by soar** [comment]
> If I understand this correctly, this is not a fix, but just a downgrade to 3.4.2
> 
> (Don't want to critizise that, thanks for the work, just mentioning: Those users who, like me, think this leads to a pre-released fixed beta-something: No, it doesn't. It's just the old package). Please correct me if I'm wrong.

Sure, I fixed the description. It's just downgrading via Brew. Not trivial for me, I thought it can be helpful.

**Comment by andreezy777** [comment]
Why no one admit that 17 days ago I have already wrote that 3.4.2 is stable version? 

https://github.com/wulkano/Kap/issues/1059#issuecomment-990862313

brrrr...

**Comment by timothyis** [comment]
Apologies all, we are working on this.

**Comment by karuppiah7890** [comment]
I'm getting an error now too -

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)

**Comment by msgongora** [comment]
Confirming this is happening in big sur also, 3.5.2
downgrading to 3.4.2
```
cd $(brew --repo homebrew/cask)
git checkout a6998a00 -- Casks/kap.rb
HOMEBREW_NO_AUTO_UPDATE=1 brew reinstall kap
```

**Comment by olivierbeaulieu** [comment]
I can reproduce this error reliably - basically I start recording, and Kap crashes if I receive a slack notification showing up in the top right while I'm recording (Big Sur 11.6)

**Comment by jadedrakerider** [comment]
I'm also getting this. It seems to be happening when I have Vysor running. I was able to successfully record earlier today. 

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)

**Comment by ionajosephine** [comment]
I tried downloading 3.4.2 but got the error: “Kap” can’t be opened because Apple cannot check it for malicious software.

**Comment by ericclemmons** [comment]
@ionajosephine per https://issuehunt.io/r/wulkano/kap/issues/1044, you can fix that error by running:

```shell
xattr -d com.apple.quarantine /Applications/Kap.app
```

**Comment by steveharman** [comment]
> I tried downloading 3.4.2 but got the error: “Kap” can’t be opened because Apple cannot check it for malicious software.

Ctrl-click / right-click on the Kap app.  This is a common Apple security issue, not a Kap bug.  You may need to re-establish screen recording & other permissions in System Preferences when asked.  I got into a loop of continuously being asked to grant a permission which already existed - the fix on my side was to remove the permission, quit Kap and re-launch it.

Again, seen that plenty of times on other apps - not a Kap issue as such.

**Comment by starryywonder** [comment]
Having this issue too for intel mac. 3.5.2 seems to be extremely laggy. Downgraded to 3.4.2 and now it's working smoothly.

**Comment by shiftkey** [comment]
Just wanted to mention that the new [`3.5.3`](https://github.com/wulkano/Kap/releases/tag/v3.5.3) build seems to have resolved this for me on Intel Mac Big Sur

**Comment by timothyis** [comment]
Thanks @shiftkey! Can anyone else confirm the latest has fixed the issue?

**Comment by pederjohnsen** [comment]
@timothyis `3.5.3` intel version seems to be working now, all though pretty slow at opening 🤔 

After clicking the Kap icon in the status bar it takes nearly 10 seconds before the recording UI is shown 😬

**Comment by starryywonder** [comment]
> Thanks @shiftkey! Can anyone else confirm the latest has fixed the issue?

Can confirm. Running 3.5.3 Intel version has fixed this. Although after pressing on the record button, it takes about 5 seconds til it actually records.

**Comment by arihid** [comment]
This bug still present in 3.5.4 Intel version when trying to record windowed region. Fullscreen record work just fine. There are +-5s delay before the record. I don't know if this is a feature or a bug. But if this is a feature, adding an actual timer would make sense imo.

**Comment by samranahm** [comment]
Seems like we still did not resolve this bug completely for intel mac.

**Comment by dafeistyone** [comment]
Issue persists
