### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by neeharmb** [wulkano/Kap#1060]
**Sentry Issue:** [KAP-9NW](https://sentry.io/organizations/wulkano-l0/issues/2322234822/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.5.1

```
Unhandled Promise Rejection

TypeError: Object has been destroyed
    at updateUi (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/dialog.js:46:30)
    at Object.action (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/utils/errors.js:144:21)
    at async /Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/dialog.js:59:17
    at async IpcMainImpl.listener (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-better-ipc/source/main.js:90:22)
```

**Comment by SuperKali** [comment]
Hi, same error

`
Unhandled Promise Rejection
TypeError: Object has been destroyed
    at updateUi (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/dialog.js:46:30)
    at Object.action (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/utils/errors.js:138:21)
    at async /Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/dialog.js:59:17
    at async IpcMainImpl.listener (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-better-ipc/source/main.js:90:22)
`

**Comment by JoshuaSoileau** [comment]
+1 I get the same. Can't make any recordings without a full reboot of my computer. Killing Kap & restarting doesn't seem to fix it.
