### ISSUE TITLE
Kap is not working in the latest MacOS version

### ISSUE THREAD

**Issue by jgonzalezalbisu** [wulkano/kap#1063]
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)

**Comment by disler** [comment]
Same

**Comment by joergRossdeutscher** [comment]
Same. 
Additionally I tried to download latest Version from https://getkap.co/ , but it gives me a version not executable on BigSure/Intel (CMD-I says: „Programm (Apple Chips)“, App has „No parking icon“)

**Comment by theapache64** [comment]
```
Recording error
Error: Could not start recording within 5 seconds
at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
```

Suddently `Kap` stopped working with above crash

**Comment by SidKH** [comment]
Downgraded to v3.4.2. It seems to work fine. 

https://github.com/wulkano/Kap/releases/tag/v3.4.2

**Comment by joergRossdeutscher** [comment]
Downgrading was a bit irritating for me, because it kept asking for permissions it had over and over, but finally it worked.

**Comment by B3DTech** [comment]
Why is it when I click download on the web page, it's automatically downloading the arm64 version? I'm running 12.1 beta, but on an Intel Mac.

**Comment by rogerleung0411** [comment]
Same here.

**Comment by timothyis** [comment]
@B3DTech Working on that in #1067 🙏🏼

**Comment by theapache64** [comment]
@SidKH Works well. Thanks

**Comment by jkincheloe33** [comment]
Any update on a fix?

**Comment by deskid** [comment]
Any progress ?

**Comment by miliberlin** [comment]
It's still not running. I miss Kap.

**Comment by jgonzalezalbisu** [comment]
Using the version https://github.com/wulkano/Kap/releases/tag/v3.4.2 works fine. You can still use it and wait for a fix for the latest version. Let's be patient!!

**Comment by brittanyjoiner15** [comment]
I deleted an older version because it was broken, and i can't reinstall - not even the 3.4.2 version😭 

Keep getting this error
![image](https://user-images.githubusercontent.com/16166290/148453238-28f601ec-0b77-415e-9118-c5fb2a54c185.png)

Super bummed 😭 I really miss it and I can't even find an alternative that i like. You've made a really cool product! Would be happy to pay for it.

**Comment by klonos** [comment]
@brittanyjoiner15 when you get the error above, try these steps:
1. click the "Show in Finder" option (which should take you to your Applications folder, with Kap selected)
2. right-click on the Kap app file (do NOT double-click), and select "Open" from the menu
3. there should be a warning, but confirming it should get Kap running

**Comment by brittanyjoiner15** [comment]
@klonos yep it appears that does work! thanks for sharing that!

**Comment by alechko** [comment]
Getting this error as well with Kap 3.5.1 on macos 12.0.1.

I really want Kap to work and I have a question about using an older version. Currently Kap installed w brew and auto updates on, but older versions are not available in brew.
Should I download the v3.4.2 release .app and override my current .app or should I remove from brew first and then install the old version?

Thanks!

**Comment by jgonzalezalbisu** [comment]
Hi @alechko ,

Please remove the one you installed with brew and then install the version mentioned here by downloading it.

Hope this helps!

**Comment by alechko** [comment]
@jgonzalezalbisu thanks! I will do that

**Comment by joergRossdeutscher** [comment]
Multiple issues have been filed about that problem here. Look a bit, in one of the thread someone has posted how                    to force brew to use a working version.

**Comment by adiun** [comment]
Just want to mention/clarify a few things since I tried following this thread:

I tried the latest version of Kap (3.5.1) and it had this error. 
* **Only version 3.4.2 will work**

After downloading and you keep seeing the `can't be opened` prompt even after [following the steps in this comment](https://github.com/wulkano/Kap/issues/1063#issuecomment-1007751259):
* Many posts out there will say to go through System Prefs -> Security & Privacy -> General -> Open Anyway. This didn't work for me.
* What did work for me was going through the terminal and running `xattr -d com.apple.quarantine /Applications/Kap.app`. Then you will get the `Kap wants to record your screen`, go to System Preferences and enable it for `Screen Recording`.

Now it works great. Thanks for making an awesome tool, it has helped me out a lot!

**Comment by sindresorhus** [comment]
Can you try out the latest version? https://github.com/wulkano/Kap/releases/tag/v3.5.2

**Comment by chen-ta0** [comment]
> 

It's still there. The same error prompt...

**Comment by joshjohanning** [comment]
3.5.2 didn't work for me (Apple M1, macOS 12.1)

**Comment by Siddharth11** [comment]
> Can you try out the latest version? https://github.com/wulkano/Kap/releases/tag/v3.5.2

@sindresorhus It didn't work for me either. System specs 👇

<img width="541" alt="Screen Shot 2022-01-18 at 11 49 16 PM" src="https://user-images.githubusercontent.com/5427715/149995680-75b98030-240e-4bd8-b384-7219dac6b2d5.png">

**Comment by jonwonglam** [comment]
3.5.2 is working for me on macOS 12.1, Apple M1. 16" M1X

**Comment by alechko** [comment]
3.5.2 is not working properly for me on macOS 12.0.1 macbook pro intel i7

it recorded once on the first launch after upgrading from 3.4.2 but then the same error appeared on second record attempt.

not sure if related, but the 3.5.* versions are super slow compared to 3.4.2, almost unresponsive. between triggering kap  either from taskbar or by keyboard shortcut there's a delay of few seconds followed by a loading mouse icon for another few seconds and then the selection window appears with the floating menu.
in 3.4.2 this process takes >1s while on 3.5.2 it takes ~15s.

`
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
`

**Comment by mbukh** [comment]
Error: Could not start recording within 5 seconds
at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.3 GHz
MACOS 12.1

**Comment by Gbuomprisco** [comment]
Hi guys, I'm getting the same error. I installed version 3.4.0, but then it automatically updated 😬 Anyone know how to disable that while the new version is broken?

**Comment by schmod** [comment]
Downgrading to 3.4.2 fixed most of the issues I've been having (including the extremely sluggish performance of 3.5.2)

I had to manually approve the new (old) version in the MacOS "Security & Privacy" preferences.

I also needed to revoke and re-grant Screen Recording permissions (also in the Security preferences).  I'm guessing the version downgrade somehow confused MacOS.

**Comment by verpixelt** [comment]
Get the same `Could not start recording within 5 seconds` error. I've tried downgrading to the mentioned 3.4.2 but macOS won't let me open it (macOS Monterey 12.1). It won't show up in Security & Privacy either.
![image](https://user-images.githubusercontent.com/1640079/151952927-c58bea54-3a54-4f04-9e92-ab2c96265249.png)

**Comment by raadopt** [comment]
Getting this error from time to time: 
Unhandled Promise Rejection 

How to stop it?

Version: 3.4.1 (3.4.1.1771) (newer version doesn't work)
on both i5 and i7 MacBook Pros
Monterey 12.2

<img width="546" alt="Screenshot 2022-02-05 at 5 29 48 PM" src="https://user-images.githubusercontent.com/56934567/152648189-a5ccf75a-6266-4bd2-865b-be5abf3d1d63.png">

**Comment by fers4t** [comment]
Both of `latest` version and `3.4.2` doesn't working on my latest version MacBook m1 :/

**Comment by fers4t** [comment]
Any update? 🙁

**Comment by svengreb** [comment]
This has been resolved since some months now with [version 3.5.4][1] which works totally fine on Apple Silicon (my system is a MacBook Pro M1 16-inch 2021 with Generation 1 chip).

[1]: https://github.com/wulkano/Kap/releases/tag/v3.5.4

**Comment by verpixelt** [comment]
@fers4t yes it works again tho still with huge initial lags. I doubt that is related.

**Comment by timothyis** [comment]
Hi all, just wondering if anyone is still seeing this error? I know about the performance issues, but wondering about the error initially noted in this issue.

**Comment by alechko** [comment]
@timothyis except for being a bit slow on my intel mbp had no issues and didn't seen the error since upgrading to 3.6.0

**Comment by visualengineer** [comment]
Love the app, thanks so much. Getting this error when installing on M2 Max, 32GB on Ventura 13.0:

Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:66)
    at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:26:129)

**Comment by lemio** [comment]
I have the same issue with Apple M1 Pro sw, 13.6.1 (22G313) with Kap-3.6.0-arm64

error:

Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:118:19)

**Comment by pinussilvestrus** [comment]
I get the same error as described in https://github.com/wulkano/Kap/issues/1063#issuecomment-1792195502

Apple M2 Pro, 14.2.1, Kap 3.6.0-arm64

Edit: worked with the fix suggested via https://github.com/wulkano/Kap/issues/1095#issuecomment-1216312778

**Comment by sopi20** [comment]
> Love the app, thanks so much. Getting this error when installing on M2 Max, 32GB on Ventura 13.0:
> 
> Unhandled Promise Rejection Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86 at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25) at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25) at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23) at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:66) at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:26:129)

source of the problem is that the node module mac-screen-capture-permissions is an intel only binary (screen-capture-permissions: Mach-O 64-bit executable x86_64), and you most probably don't have rosetta installed. It would be great if someone could do a proper Apple Silicon native build of kap (including the node modules), or a proper universal binary (including node modules)... although in this case it looks like the problem might be in the mac-screen-capture-permissions dependency iteself :/

**Comment by sopi20** [comment]
I just tried building it from source with changed version of mac-screen-capture-permissions from 1.1.0 to 2.1.0 and after yarn dist it appears to work just fine (although I tried only recording one whole screen recording, so maybe more testing should be done before that is accepted as a solution to this problem)

**Comment by codercodingthecode** [comment]
Check this https://github.com/wulkano/Kap/issues/1231, I have addressed the intel dependency issue. Rosetta is no longer required.

**Comment by x0d7x** [comment]
app running as processes but not showing to record the screen it was working fine   
![image](https://github.com/user-attachments/assets/c7531187-5132-47a3-9991-8e20c54136eb)
