### ISSUE TITLE
Recording error

### ISSUE THREAD

**Issue by cliffzhaobupt** [wulkano/Kap#1064]
**Sentry Issue:** [KAP-B8X](https://sentry.io/organizations/wulkano-l0/issues/2849782220/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.5.1

```
Recording error

Error: Command failed with exit code 1: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture record --process-id dl2mjn1jame {"destination":"file:///private/var/folders/9r/_z00151101dbhh8zt2hpq7dj71bw00/T/1b0e870599af482c35e7a0dc1593df7b.mp4","framesPerSecond":30,"showCursor":true,"highlightClicks":false,"screenId":2077750265,"cropRect":[[196,64],[1292,921]],"videoCodec":"avc1"}
Error Domain=AVFoundationErrorDomain Code=-11806 "Recording Stopped" UserInfo={AVErrorRecordingSuccessfullyFinishedKey=true, NSLocalizedDescription=Recording Stopped, NSLocalizedRecoverySuggestion=Try recording again.}
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:118:26)
```

**Comment by raminious** [comment]
I faced same issue

macOS: 12.1 - M1 Pro
Kap: 3.5.1

```
Recording error
Error: Command failed with exit code 1: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture record --process-id p500uwuyhjq {"destination":"file:///private/var/folders/xd/9672rzgd0pvfh37ml2wtn3y40000gn/T/dc3958baff3d863b533d42f02bf8da46.mp4","framesPerSecond":30,"showCursor":true,"highlightClicks":false,"screenId":1,"cropRect":[[15,98],[1701,940]],"videoCodec":"avc1"}
Error Domain=AVFoundationErrorDomain Code=-11806 "Recording Stopped" UserInfo={AVErrorRecordingSuccessfullyFinishedKey=true, NSLocalizedDescription=Recording Stopped, NSLocalizedRecoverySuggestion=Try recording again.}
at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/lib/error.js:60:11)
at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:118:26)
Reporting this issue will help us track it better and resolve it faster.
```

**Comment by digitalmaster** [comment]
This one's pretty tough because it error's after recording. Meaning we loose what we just recorded :(

**Comment by sindresorhus** [comment]
https://github.com/wulkano/Kap/releases/tag/v3.5.4

**Comment by christoph-kluge** [comment]
I've installed 3.4.5 (M1) on Monterey (12.3) and Kap crashed during recording. The error-report sent me directly here.

**Comment by timothyis** [comment]
Hi @christoph-kluge. 3.4.5 is an old version, could you try updating?

**Comment by christoph-kluge** [comment]
@timothyis sorry. I had a number-typo in my message. It's 3.5.4.

<img width="299" alt="Screenshot 2022-05-02 at 10 29 22" src="https://user-images.githubusercontent.com/1446269/166206449-bb326c72-7090-4ade-9eac-cec8c2330cb0.png">

**Comment by carlosbaraza** [comment]
This issue is still happening after recording

**Comment by andreasotto** [comment]
Happening here, too :-(

Reproducible, 100% of the tests

M1 Macstudio. 

This has worked before with macOS 12, but in the meantime 13 is up to date. Whether it has something to do with that, I can't say. Kap is freshly installed, first call after installation. Version 3.6.0 (3.6.0.1846) I hope the bug can be fixed quickly. If I can support in any way, please just let me know.

**Comment by timothyis** [comment]
Thanks for reporting, all.

**Comment by eadgbear** [comment]
I get this when recording with keystrokes visible and typing in Japanese

**Comment by schalkneethling** [comment]
I ran into this one twice in a row. I can reproduce it reliably by pressing the escape key while recording.

macOS Ventura
Macbook Air M2 Chip
Kap version 3.6.0.1846

**Comment by jeremytdakin** [comment]
Can replicate this with a 100% success (or I guess fail) rate when trying to screen record my development in Godot with the game running. 

macOS Sonoma 14.5
Macbook Pro M1 Pro
Latest Kap
