### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by jamescrowley** [wulkano/Kap#1065]
**Sentry Issue:** [KAP-ATH](https://sentry.io/organizations/wulkano-l0/issues/2671248295/)

**macOS version:**    Monterey (12)
**Kap version:**      3.5.1

```
Unhandled Promise Rejection

Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at Object.ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist-js/index.js:102:30
```

**Comment by timothyis** [comment]
Closing as a duplicate of #1095 — same spawnSync/SIGTRAP/"Unknown system error -86" signature (mac-screen-capture-permissions).
