### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by chrszlz** [wulkano/Kap#1070]
**Sentry Issue:** [KAP-ATG](https://sentry.io/organizations/wulkano-l0/issues/2670926435/)

**macOS version:**    Monterey (12)
**Kap version:**      3.5.1

```
Unhandled Promise Rejection

Error: Command was killed with SIGTRAP: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/lib/error.js:59:11)
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:187:17)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at Object.ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:31)
    at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:18:129)
```

MacBook Pro (14-inch, 2021)
Apple M1 Max
macOS - 12.0.1 (21A559)

Menu bar app loads. Preferences and all native system windows work. Clicking primary action in menu bar immediately crashes

**Comment by timrogers** [comment]
This one is hitting me as soon as I open the app, before I see any menu bar item, preferences, etc. I have a 2022 16" M1 Max MacBook Pro.

**Comment by jlingertat** [comment]
same here. 
Is these a fix for it?

**Comment by djpowers** [comment]
I'm experiencing this issue as well, also seeing it on an Apple M1 MacBook Pro. This device does _not_ have Rosetta 2 installed. It is working on a different M1 machine that is using Rosetta, so I wonder if that may have something to do with it.

**Comment by brittanyjoiner15** [comment]
Also hitting this 😭

**Comment by codercodingthecode** [comment]
Still a problem today from January.
I will look into this next week if no resolution yet by then.

**Comment by KittyLomas** [comment]
still experiencing this. had to reset my computer and therefore redownload kap and now I can't open it. getting error below. 

```
Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:66)
    at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:26:129) 
```

Included a screenshot of the version of my macbook 

<img width="522" alt="Screen Shot 2024-06-11 at 4 48 42 pm" src="https://github.com/wulkano/Kap/assets/32585489/67913528-88a3-4816-b057-62458b98d1bd">

**Comment by yusuftryoto** [comment]
same with mac os 15.0 seqouia

**Comment by codercodingthecode** [comment]
I just provided a fix for this.
check here https://github.com/wulkano/Kap/issues/1231

**Comment by timothyis** [comment]
Closing as a duplicate of #1095 — same spawnSync/SIGTRAP/"Unknown system error -86" signature (mac-screen-capture-permissions).
