### ISSUE TITLE
Error when clicking record buton

### ISSUE THREAD

**Issue by youssefavx** [wulkano/Kap#1071]
**Sentry Issue:** [KAP-BDC](https://sentry.io/organizations/wulkano-l0/issues/2913396349/)

**macOS version:**    Mojave (10.14)
**Kap version:**      3.5.1

```
Error

Error: Command was killed with SIGABRT (Aborted): /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture list audio-devices
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture
  Reason: image not found
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:118:26)
    at async Function.module.exports.audioDevices (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:244:19)
    at async Object.getAudioDevices (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/utils/devices.js:54:29)
    at async Object.initializeDevices (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/utils/devices.js:95:25)
```

**Comment by youssefavx** [comment]
It also says "aperture quit unexpectedly" and similar error happens when clicking three dots on the menu

**Comment by artificial-cassiano** [comment]
I had a similar error

```
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
    
 ```

**Comment by verpixelt** [comment]
Exact same here unfortunately
```
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
```

**Comment by sindresorhus** [comment]
Can you try https://github.com/wulkano/Kap/releases/tag/v3.5.3 ?

**Comment by verpixelt** [comment]
Thanks @sindresorhus! 🎉 I've tried it and it works. It's very sluggish on startup, ran into the beachball of death multiple times but it does the trick.

**Comment by timothyis** [comment]
Closing because no additional reports and the reports already in this issue are duplicates of #1063
