### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by deiay** [wulkano/Kap#1083]
**Sentry Issue:** [KAP-BG0](https://sentry.io/organizations/wulkano-l0/issues/2939306878/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.5.1

```
Unhandled Promise Rejection

Error: sha512 checksum mismatch, expected TtHyDo2gPq3VyToaIWgPPFVv/vLjKE6XfCYcTQ3I9lTPL9SyQSZI/v8WYx9yNqw6RELmC/C8r1rU5P9E3PBGTw==, got YC/Vt0GIR3M/J/JRiUu76ZbgGpmJfABmd+1knWuTlxQRhqBRwN50hrV9nN4yRvKq5cHey3ppN80eDoAmEw/RPA==
    at Object.newError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)
    at DigestTransform.validate (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:323:27)
    at DigestTransform._flush (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:309:22)
```

**Comment by timothyis** [comment]
Hi @deiay, would you mind trying this on the latest version?
