### ISSUE TITLE
`mac-screen-capture-permissions` causing Unhandled Promise Rejection

### ISSUE THREAD

**Issue by zmk-punchbowl** [wulkano/Kap#1095]
**Sentry Issue:** [KAP-BPC](https://sentry.io/organizations/wulkano-l0/issues/2991381748/)

**macOS version:**    Monterey (12)
**Kap version:**      3.5.3

```
Unhandled Promise Rejection

Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist-js/index.js:102:65
```

**Comment by timothyis** [comment]
Could this possibly be fixed by updating `mac-screen-capture-permissions` @karaggeorge? Asking since it's your package so you may know a bit more here.

**Comment by mmeyer724** [comment]
As a troubleshooting step I tried manually granting Kap screen recording access (System Prefs -> Security -> Screen Recording -> Click '+' and add Kap.app), but that did not help unfortunately

**Comment by 0-Chan** [comment]
I have the same problem here.
Adding kap.app to security didn't help either. Any progress?

(macOS 12.3.1, M1)

**Comment by Bolza** [comment]
Same issue here
(macOS 12.4, M1)

**Comment by jaro-io** [comment]
for me a simple reinstall fixed the problem. :man_shrugging:

**Comment by 0-Chan** [comment]
Wow... reinstall really fixes the problem. Thanks!

**Comment by nyjr10025** [comment]
Confirmed on MacOS, 12.3.1, M1 that a reinstall fixes permissions issue mentioned above

**Comment by djpowers** [comment]
I'm still seeing this on macOS 12.4 on an M1 computer. I tried a full reinstall, and also manually adding the screen recording permissions for Kap, but no luck. This machine currently does not have Rosetta installed, which could possibly be a factor (another machine with the same specs that **does** have Roesetta installed is _not_ having this problem).

**Comment by djpowers** [comment]
Digging into this a little more, the  `Unknown system error -86` messaging makes me fairly confident this is due to some upstream dependency not being compatible with M1 machines. I suspect installing Rosetta would resolve this (ideally Rosetta would not be required, or at least a more graceful failure would be in place). I've seen this error on other applications though that required Rosetta in order to work.

(The "collect and report" option for this crash takes me to https://github.com/wulkano/Kap/issues/1106, which was marked as a duplicate of https://github.com/wulkano/Kap/issues/1070, but this does appear to be a distinct issue based on the trace.)

**Comment by pedros007** [comment]
I ran into this after upgrading from Big Sur to Monterey.  I was eventually able to get things working after trying the following a few times:
```sh
brew install --cask kap
open /Applications/Kap.app
```
When the System Preferences `Privacy` dialogue came up, I  pressed `-` to remove Kap. I then clicked `+` to add `/Applications/Kap.app`. Quit Kap & re-open. I tried variations of this a few times and it didn't work... so your mileage may vary!

Also, the Kap issue tracker has a bunch of seemingly duplicate issues related to this problem.

**Comment by sindresorhus** [comment]
I had to revert #1129 as it causes problem when built for production. The binary used in the capture permission thing could not be found and I don't have time to look into it. If someone wants to work on this, make sure you test the change by running `npm run dist` and try launching the app in the `dist` folder.

**Comment by xstast24** [comment]
Hi, just confirming that this issue persists. MacBook Pro 2021 (Apple arm CPU, Mojave OS).
Kap doesn't work at all. I tried to reinstall Kap / reallow permissions / reboot mac around 10 times in various orders (as suggested above), but it didn't help. I love Kap and am looking forward to using it again, I hope somebody knows how to fix this. Thanks in advance, fingers crossed 😉 🤞

**Comment by thethomasz** [comment]
Woops, didn't notice the prebuilts for that package weren't uploaded. I tried to see if it was possible to fix the github action that creates the prebuilts, but the `prebuild` library fails to upload the binaries to the release, and I'm not entirely sure why. Also, I don't think github has ARM Mac runners yet (can track it here https://github.com/github/roadmap/issues/528), so we'd also need to upload the prebuilts from their own self hosted ARM Mac, or just skip using prebuilts on ARM Macs.

Although with version 3.5.5, the error doesn't seem to come up for me anymore. For anyone that had issues installing Kap 3.5.4, try installing 3.5.5 to see if it fixes the issue. If the issue persists, we might need to address the issues I mentioned above, or use this library instead https://github.com/codebytere/node-mac-permissions#permissionsaskforscreencaptureaccess.

**Comment by xstast24** [comment]
> 
Hi, on Macbook Pro 2021 (arm CPU, MacOS Mojave) with Kap 3.5.5:
- if Rosetta (x86_64 emulator) is NOT installed, Kap raises the exception and doesn't work at all
- if Rosetta is installed, Kap works
--> Kap is not working on the pure ARM, but it works with the Rosetta emulator "workaround".

PS: To install Rosetta, run `softwareupdate --install-rosetta --agree-to-license`

**Comment by philfreo** [comment]
Any chance of getting a fix for this for Macs without Rosetta installed?

**Comment by lx-wnk** [comment]
This error also occurs for me

* MacBook Pro (M1 Pro - 2021)
* macOS Ventura 13.1
* Kap version: 3.6.0

```
Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:66)
    at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:26:129)
```


UPDATE (25.09.23):
For me the issue is resolved. I'm currently on 
* MacBook Pro (M1 Pro - 2021)
* macOS Ventura 13.5.2
* Kap version: 3.6.0

**Comment by JdesEva** [comment]
I believe I have fixed the issue. Please see this MR.

https://github.com/wulkano/Kap/pull/1181

**Comment by Qwertic** [comment]
After reinstalling the app the issue is not present anymore

**Comment by alvarotrigo** [comment]
I did two things and the error went away:
- Restarted my Mac (MacBook Pro M2)
- Installed Rosetta for old intel apps  (even though I'm using the latest KAP version for Apple Silicon)

**Comment by g-guerzoni** [comment]
> I did two things and the error went away:
> 
> * Restarted my Mac (MacBook Pro M2)
> * Installed Rosetta for old intel apps  (even though I'm using the latest KAP version for Apple Silicon)

@alvarotrigo Thanks, it worked.

For those who want to make this workaround:
- Run in the terminal: `softwareupdate --install-rosetta`
- Re-open the app

**Comment by khurshid-alam** [comment]
Same error on MacBook Air M1. And Rosetta crashes on me. So doesn't work.

**Comment by pixelbud** [comment]
Installing Rosetta via Terminal worked for me. Did not have to reinstall or re-open the app.

**Comment by thatlamguy** [comment]
Confirmed working for M4 with Rosetta 2

**Comment by cblair** [comment]
This worked for me as well, new Mac M3 on OSX 15.2.

**Comment by neilbaldwin** [comment]
The Rosetta workaround worked for me too. Odd but I'm glad it's working again! Thanks @alvarotrigo 👍

**Comment by dikarel** [comment]
Just tried this fix (`softwareupdate --install-rosetta`) -- it works for me on Apple M4 Max

**Comment by ramisuarez** [comment]
Can confirm `softwareupdate --install-rosetta` in terminal fixed it for me also. Macbook Air M4.

**Comment by Joseph-D-Bradshaw** [comment]
Still an issue in Aug 2026

Using Rosetta as a work around, but this is an issue that will kill Kap eventually due to Intel based programs being unsupported in future MacOS versions
