### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by YaChenHsieh** [wulkano/kap#1190]
**Sentry Issue:** [KAP-TTQ](https://wulkano-l0.sentry.io/issues/4339673089/)

**macOS version:**    Mojave (10.14)
**Kap version:**      3.6.0

```
Unhandled Promise Rejection

Error: Command was killed with SIGABRT (Aborted): /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture events listen --process-id kf9suc3r958 --exit onFileReady
dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture
  Reason: image not found
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:118:26)
    at async Aperture.waitForEvent (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:161:20)
    at async /Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:136:5
```

**Comment by tonyshixd** [comment]
iMac 21.2, macOS 14.1
Can verify that manually installing Rosetta 2 solved this issue

`softwareupdate --install-rosetta`
