### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by JamesMilazzo** [wulkano/kap#1193]
**Sentry Issue:** [KAP-BPX](https://wulkano-l0.sentry.io/issues/2993034693/)

**macOS version:**    Unknown ()
**Kap version:**      3.6.0

```
Unhandled Promise Rejection

TypeError: Cannot destructure property 'filePath' of 'exports.recordingHistory.get(...)' as it is undefined.
    at stopCurrentRecording (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/recording-history.js:96:13)
    at stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/aperture.js:186:54)
```

**Comment by egoens** [comment]
I closed my issue so I can keep this issue on track. I am experiencing the same (or similar) error on an M1 Mac:

```
Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:66)
    at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:26:129)
```

![image](https://github.com/wulkano/Kap/assets/8153/19bb29b5-fa94-46a1-b1bd-937280484bc7)

**Comment by GilangIRSYD** [comment]
open terminal and run `softwareupdate --install-rosetta --agree-to-license`

**Comment by codercodingthecode** [comment]
no need for rosetta, see this https://github.com/wulkano/Kap/issues/1231
