### ISSUE TITLE
Crash on start M3 Pro

### ISSUE THREAD

**Issue by colymba** [wulkano/Kap#1206]
**Sonoma 14.1 Apple M3 Pro**
**Kap version: Version 3.6.0 (3.6.0.1846)**

#### Steps to reproduce
Download latest M1 release from site
Install
Launch
Error when opening Kap

#### Current behaviour
Crash on launch recorder

```
Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at Object.openCropperWindow [as open] (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/windows/cropper.js:81:66)
    at Object.openCropperWindow (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/tray.js:26:129)
```

**Comment by polimorficzny** [comment]
+1

**Comment by walkerdb** [comment]
Works fine on my M3 Max, on macOS 14.3.1. Have you given kap screen recording permissions from macOS settings?

<img width="717" alt="Screenshot 2024-02-12 at 10 08 39 PM" src="https://github.com/wulkano/Kap/assets/7026330/5557a9be-9e66-4082-a886-dec17ca3a501">

**Comment by colymba** [comment]
@walkerdb yes... everything setup and installed normally.
<img width="501" alt="image" src="https://github.com/wulkano/Kap/assets/978040/7c68b2d1-5afe-4fdc-9152-aa35d9180449">

**Comment by jaanli** [comment]
Also having this issue.

**Comment by carstenhag** [comment]
Workaround can be found at https://github.com/wulkano/Kap/issues/1095#issuecomment-1216312778

**Comment by GilangIRSYD** [comment]
open terminal and run `softwareupdate --install-rosetta --agree-to-license`

**Comment by cdx111** [comment]
Also having this issue.

**Comment by enoola** [comment]
Hello, same here.

**Comment by codercodingthecode** [comment]
See this https://github.com/wulkano/Kap/issues/1231

**Comment by timothyis** [comment]
Closing as a duplicate of #1095 — same spawnSync/SIGTRAP/"Unknown system error -86" signature (mac-screen-capture-permissions).
