### ISSUE TITLE
Error-while activation mic on mac os 18

### ISSUE THREAD

**Issue by yusuftryoto** [wulkano/kap#1229]
**Sentry Issue:** [KAP-VBV](https://wulkano-l0.sentry.io/issues/5355747626/)

**macOS version:**    Unknown ()
**Kap version:**      3.6.0

```
Error

Error: Command failed with Unknown system error -86: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices list --input --json
spawn Unknown system error -86
    at execa (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/node_modules/execa/index.js:80:26)
    at Object.module.exports.<computed> (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/index.js:10:26)
    at Object.getAudioDevices (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/utils/devices.js:38:44)
    at electron/js2c/browser_init.js:221:8665
    at IpcMainImpl.<anonymous> (electron/js2c/browser_init.js:221:5052)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10038)
```

**Comment by yusuftryoto** [comment]
mac os 15.0 sequoia
