### ISSUE TITLE
MacOS M1 CPU Screen Recording Permission Issue [Fix]

### ISSUE THREAD

**Issue by codercodingthecode** [wulkano/kap#1231]
# MacOS M1 CPU Screen Recording Permission Issue [Fix]

## Issue
Many users have reported screen permission issues on M1 Macs, with some resorting to installing Rosetta despite using an M1-specific build. The root cause is that the node package used to request permissions is based on Intel architecture, thus requiring Rosetta on M1 chips.

## Solution
I've made the following modifications to resolve this issue:

1. Upgraded Node.js version to 16 to use M1 APIs natively.
2. Removed the Intel-dependent library `mac-screen-capture-permissions`.
3. Utilized Electron's native API support for permission requests.

These changes allow the app to request and use screen recording permissions on M1 Macs without the Rosetta workaround.

## Implementation Details
1. Updated `package.json` to use Node.js 16.
2. Removed `mac-screen-capture-permissions` from dependencies.
3. Modified the screen capture permission code to use Electron's `systemPreferences` API:

## Application
I've built the release version of the app with these changes, and it's available in the `release` section of my forked repository.

1. Download the zipped app from `release`.
2. Unzip and move it to the Applications folder.
3. Grant the necessary permissions.
4. Launch the app and verify that screen recording works without Rosetta.

This solution should allow Kap to function natively on M1 Macs without any Intel-based dependencies for screen recording permissions.

https://github.com/codercodingthecode/Kap/releases/download/m1-permission/Kap.zip

If there is an interest from the maintainers, I can open a pr with these changes to the main project.
 
 
<img width="855" alt="image" src="https://github.com/user-attachments/assets/2782ce8b-e425-4ffb-ae96-b0d6d8cb91d5">

![Kapture 2024-09-20 at 13 39 14](https://github.com/user-attachments/assets/8d12fa8a-6cb4-424e-aa5d-3b0e8d2ca2cc)

**Comment by boodaah3d** [comment]
As of today, I get this error message on the new Mac Mini M4 base model.

```
Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist-js/index.js:104:65
```

So I went to [codercodingthecode](https://github.com/codercodingthecode)'s fork and download their release but I get this error dialog.

![Screenshot 2024-11-29 at 6 44 26 PM](https://github.com/user-attachments/assets/32a17394-7c14-4911-b6b8-05ede76b4b17)

**Comment by codercodingthecode** [comment]
I will take a look at this.
@boodaah3d  Please let me know if you deleted the previously installed app before trying the new one.
I ran into a similar issue because I had forgotten to remove the old broken one from the installation folder.

**Comment by boodaah3d** [comment]
This was a new Mac mini and I installed the latest version here and got the error message. And then I read the thread here and tried the version from the fork. Those were the only versions installed on the system ever.

When I downloaded the fork, I just replaced the other version in the application folder.

**Comment by codercodingthecode** [comment]
@boodaah3d Replacing won't work, you need to remove the old file manually and then re-do the installation with the fork.
I believe there is a cache in the system, just replacing the current app with another[same] app with slightly different content is causing the issue.

**Comment by codercodingthecode** [comment]
follow these steps:
download the file, i have updated it.
then unzip and right click to bring up the floating menu and select open
![image](https://github.com/user-attachments/assets/1418bf61-93da-4a38-a2d2-deb5435abb1a)

then you will get this 
![image](https://github.com/user-attachments/assets/8b45b0ec-77d3-4893-bd97-44adb8d81f00)

then click ok and repeat the step above and will get a slightly different  option:
![image](https://github.com/user-attachments/assets/83b34949-5336-4a80-9617-4571cd6a7dfd)

select open and you will get this:
![image](https://github.com/user-attachments/assets/9b670b87-9873-4011-a032-c8979a62746f)

Before selecting move to application folder, make sure you have removed/deleted the older version from that folder and no other copy is running.
after that it should open and ask for the OS permissions, etc.

**Comment by boodaah3d** [comment]
I followed the steps and got this .. 
Unhandled Promise Rejection
Error: Invalid media type
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:67:34)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist-js/index.js:104:65
    


But the app seemed to be running so I attempted to make a recording and got this ..

Recording error
Error: Command failed with exit code 1: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture record --process-id fhr3b1pu8y5 {"destination":"file:///private/var/folders/x2/wyvjk99d2pdcyrx7sm6cm0d80000gn/T/986578f9df237651c1facf2a2b5fa432.mp4","framesPerSecond":30,"showCursor":true,"highlightClicks":false,"screenId":2,"cropRect":[[1720,204],[688,516]],"videoCodec":"avc1"}
Error Domain=AVFoundationErrorDomain Code=-11805 "Cannot Record" UserInfo={NSLocalizedRecoverySuggestion=Try recording again., NSLocalizedDescription=Cannot Record, AVErrorRecordingSuccessfullyFinishedKey=false}
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:118:26)

**Comment by ayoungh** [comment]
> I followed the steps and got this .. Unhandled Promise Rejection Error: Invalid media type at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:67:34) at /Applications/Kap.app/Contents/Resources/app.asar/dist-js/index.js:104:65
> 
> But the app seemed to be running so I attempted to make a recording and got this ..
> 
> Recording error Error: Command failed with exit code 1: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture record --process-id fhr3b1pu8y5 {"destination":"file:///private/var/folders/x2/wyvjk99d2pdcyrx7sm6cm0d80000gn/T/986578f9df237651c1facf2a2b5fa432.mp4","framesPerSecond":30,"showCursor":true,"highlightClicks":false,"screenId":2,"cropRect":[[1720,204],[688,516]],"videoCodec":"avc1"} Error Domain=AVFoundationErrorDomain Code=-11805 "Cannot Record" UserInfo={NSLocalizedRecoverySuggestion=Try recording again., NSLocalizedDescription=Cannot Record, AVErrorRecordingSuccessfullyFinishedKey=false} at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/lib/error.js:60:11) at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:118:26)

Same for me :(
