### ISSUE TITLE
Unhandled Promise Rejection Error on Apple M3

### ISSUE THREAD

**Issue by calinday** [wulkano/Kap#1233]
```
Unhandled Promise Rejection
Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions
spawnSync /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/mac-screen-capture-permissions/screen-capture-permissions Unknown system error -86
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/node_modules/execa/index.js:168:25)
    at exports.hasScreenCapturePermission (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/mac-screen-capture-permissions/index.js:27:25)
    at ensureScreenCapturePermissions (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/common/system-permissions.js:64:23)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist-js/index.js:104:65
```

**macOS version:**
Apple M3
Sonoma 14.7 (23H124)

**Comment by codercodingthecode** [comment]
a solution to this issue is 2 posts below yours, check this https://github.com/wulkano/Kap/issues/1231

**Comment by calinday** [comment]
I saw that but was unable to find where "release" was on his profile. Sorry
for not knowing the github interface that well but can you point me to it?
[image: image.png]

**Comment by codercodingthecode** [comment]
gotcha, go to this page and download the zip file https://github.com/codercodingthecode/Kap/releases/tag/m1-permission <br>
Unzip the file and move it to the Applications folder.
![image](https://github.com/user-attachments/assets/3d8750bd-0c31-46e2-9b57-2d87382ca55b)

**Comment by calinday** [comment]
oh awesome, thank you kindly.

**Comment by timothyis** [comment]
Closing as a duplicate of #1095 — same spawnSync/SIGTRAP/"Unknown system error -86" signature (mac-screen-capture-permissions).
