### ISSUE TITLE
Suggest new feature: recording device audio

### ISSUE THREAD

**Issue by Partysun** [wulkano/kap#145]
Hi, it's an awesome app! Thank you..  
I suggest new feature - recording device audio. (like in screenFlow app)
Now we can record mic, but sometimes users will try to record audio from his apps/demos.

**Comment by sindresorhus** [comment]
The only way to achieve this with macOS Sierra, because of System Integrity Protection, is an Apple signed and approved kernel extension. That is what Screenflow does. I don't think we'll be able to do that.

What we could do is to have a link in preferences that opens a guide on how to achieve it with Kap, using [Soundflower](https://www.fluxforge.com/blog/soundflower-os-x-10.11-10.12-macOS-sierra/) (free) or [Loopback](https://rogueamoeba.com/loopback/) (free for 20min per recording).

**Comment by doot0** [comment]
I found this, which could potentially go some ways to making this a possibility but I fear that the added complexity could be a pain in the butt - https://github.com/ZECTBynmo/node-core-audio

**Comment by luksak** [comment]
+1

**Comment by ahrorkosimi** [comment]
is it possible to record audio from app if I turn of SIP? It is really needed feature to be able to record video and audio from app for demo purposes.

**Comment by karaggeorge** [comment]
@Partysun @doot0 @ahrorkosimi (or anyone else following this)

Could you guys test our work in progress solution for this? We are utilizing soundflower as described above, but created a plugin which takes care of creating the devices, setting them during the recording and cleaning up after.

To test, you'll need to install [soundflower](https://github.com/mattingalls/Soundflower) first, and then download [this build](https://1527-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg), go to Preferences -> Plugins, install `soundflower`, and try to record.

You can also try messing with the plugin settings, but by default, you should be able to record system audio, while also being able to hear it while recording, and it should record system audio in addition to your specified input source (if any).

**Comment by meshulam** [comment]
@karaggeorge that build worked great for me! I didn't have to change any of the plugin settings for it to pick up both my mic and the system audio. 

It wasn't immediately clear to me what the volume setting in the plugin was supposed to do. I was afraid I would have to adjust it to keep my speaker volume consistent when toggling recording on and off, but it seems like more of an advanced setting that should be ok staying at 1 in most cases. Maybe it should be moved below the "combine input/output" settings since users are more likely to want to change those?

**Comment by aantix** [comment]
Since Soundflower is MIT, is there any way to package it with Kap and have it installed seamlessly alongside the Kap installation?  

Instead of a separate Soundflower installation.

**Comment by dcst55** [comment]
> @Partysun @doot0 @ahrorkosimi (or anyone else following this)
> 
> Could you guys test our work in progress solution for this? We are utilizing soundflower as described above, but created a plugin which takes care of creating the devices, setting them during the recording and cleaning up after.
> 
> To test, you'll need to install [soundflower](https://github.com/mattingalls/Soundflower) first, and then download [this build](https://1527-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg), go to Preferences -> Plugins, install `soundflower`, and try to record.
> 
> You can also try messing with the plugin settings, but by default, you should be able to record system audio, while also being able to hear it while recording, and it should record system audio in addition to your specified input source (if any).

Is it possible to record only the System Sound (without the build-in micro) AND is it possible to record the System-Audio without playing it over the speakers? that would be great!

**Comment by karaggeorge** [comment]
Hey @dcst55 ,

yeah both of those are possible. For the microphone one, you could just disable audio recording in Preferences, or use the plugin settings to only record system sound. The second one can only be disabled in the plugin settings. To get there, open Preferences -> Plugins -> soundflower -> click the pencil icon, and then adjust the settings as you see fit. Let me know if any of them don't work for you

**Comment by karaggeorge** [comment]
@meshulam 

You're right, I can move that down more. That is the volume at which the system sound will be played in the recording. Do you think a setting for what the computer (speaker) volume should be set to or is keeping it to where the user had it before the recording is ok?

**Comment by karaggeorge** [comment]
@aantix 
Not sure how we can package the kernel extension within Kap and have that install at the same time, since it needs extra permissions

**Comment by dcst55** [comment]
> Hey @dcst55 ,
> 
> yeah both of those are possible. For the microphone one, you could just disable audio recording in Preferences, or use the plugin settings to only record system sound. The second one can only be disabled in the plugin settings. To get there, open Preferences -> Plugins -> soundflower -> click the pencil icon, and then adjust the settings as you see fit. Let me know if any of them don't work for you

it dont work for me...

I get the following Error Message:

```
Error: Built-in Microphone is not an output device
    at throwIfStderr (/Users/<USER>/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/index.js:22:11)
    at module.exports.<computed> (/Users/selcuk/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/index.js:11:12)
    at async Object.willStartRecording (/Users/selcuk/Library/Application Support/Kap/plugins/node_modules/kap-soundflower/index.js:68:5)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:39:7
    at async Promise.all (index 0)
    at async Object.startRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:129:3)
```

**Comment by dcst55** [comment]
> @Partysun @doot0 @ahrorkosimi (or anyone else following this)
> 
> Could you guys test our work in progress solution for this? We are utilizing soundflower as described above, but created a plugin which takes care of creating the devices, setting them during the recording and cleaning up after.
> 
> To test, you'll need to install [soundflower](https://github.com/mattingalls/Soundflower) first, and then download [this build](https://1527-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg), go to Preferences -> Plugins, install `soundflower`, and try to record.
> 
> You can also try messing with the plugin settings, but by default, you should be able to record system audio, while also being able to hear it while recording, and it should record system audio in addition to your specified input source (if any).

will Soundflower be compatible with MacOS Catalina? I'm using MacOS Catalina and it don't work stable for me...

**Comment by karaggeorge** [comment]
> > Hey @dcst55 ,
> 
> > 
> 
> > yeah both of those are possible. For the microphone one, you could just disable audio recording in Preferences, or use the plugin settings to only record system sound. The second one can only be disabled in the plugin settings. To get there, open Preferences -> Plugins -> soundflower -> click the pencil icon, and then adjust the settings as you see fit. Let me know if any of them don't work for you
> 
> 
> 
> it dont work for me...
> 
> 
> 
> I get the following Error Message:
> 
> 
> 
> ```
> 
> Error: Built-in Microphone is not an output device
> 
>     at throwIfStderr (/Users/<USER>/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/index.js:22:11)
> 
>     at module.exports.<computed> (/Users/selcuk/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/index.js:11:12)
> 
>     at async Object.willStartRecording (/Users/selcuk/Library/Application Support/Kap/plugins/node_modules/kap-soundflower/index.js:68:5)
> 
>     at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:39:7
> 
>     at async Promise.all (index 0)
> 
>     at async Object.startRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:129:3)
> 
> ```

Hey @dcst55

Can you please share what settings you had on when you got this error? That seems like a plugin error which I can work on fixing

**Comment by leafac** [comment]
This worked great for me on Catalina 👍

**Comment by devnoname120** [comment]
Soundflow isn't available on Apple silicon. Is there an alternative?
I couldn't get it to work with Blackhole 2ch.

**Comment by leafac** [comment]
@devnoname120 I use BlackHole on a Mac with the M1 processor. I can assist you in getting it working if you provide some more information. What you tried, what went wrong, what error messages you saw, and that sort of thing.

**Comment by devnoname120** [comment]
@leafac I can confirm that I've followed https://github.com/ExistentialAudio/BlackHole/wiki/Multi-Output-Device and https://github.com/ExistentialAudio/BlackHole/wiki/Aggregate-Device — it works now! My virtual devices were not properly configured.

**Comment by seahindeniz** [comment]
Here's YouTube video of how to install BlackHole

https://www.youtube.com/watch?v=F67Jj5QCct8

**Comment by luokunman** [comment]
> @Partysun @doot0 @ahrorkosimi（或其他任何关注此的人）
> 
> 你们可以为此测试我们正在进行的解决方案吗？如上所述，我们正在使用 soundflower，但创建了一个插件来负责创建设备、在录制期间设置它们并在之后进行清理。
> 
> 要进行测试，您需要先安装[soundflower](https://github.com/mattingalls/Soundflower)，然后下载[此版本](https://1527-65411043-gh.circle-artifacts.com/0/dist/Kap.dmg)，转到 Preferences -> Plugins，安装`soundflower`，然后尝试录制。
> 
> 您也可以尝试弄乱插件设置，但默认情况下，您应该能够录制系统音频，同时也能够在录制时听到它，并且除了您指定的输入源（如果有）之外，它还应该录制系统音频.

soundflower cannot support M1.

**Comment by eisenbruch** [comment]
So once we have BlackHole setup is there a way to route it through to Kap?

Seems like this still needs to be added.

5 year old issue.

Is someone working on adding this?

**Comment by timothyis** [comment]
Kap is open-source, you are more than welcome to take a look at this issue @eisenbruch!

**Comment by thearnica** [comment]
Found an easy way to record what I need:
- install [Background Music](https://github.com/kyleneideck/BackgroundMusic#recording-system-audio)
- set it as a microphone to Kap
- ✅ you are recording "internal sound"
----
To mix with microphone:
- create new aggregate device
- set add you mic and BackgroundMusic
- ✅ use it as microphone for Kap
----
Mac 13.0 will add support for audioCapture for ScreenCaptureKit - https://developer.apple.com/documentation/screencapturekit/scstreamconfiguration/3955571-capturesaudio, until then I haven't found a good way to tap into computer audio.
However Zoom shares music without any problem. There should be a way....

**Comment by eisenbruch** [comment]
> * install [Background Music](https://github.com/kyleneideck/BackgroundMusic#recording-system-audio)
> * set it as a microphone to Kap
> * ✅ you are recording "internal sound"

Can confirm this works. Thanks @thearnica !

**Comment by timothyis** [comment]
Thank you for sharing this @thearnica!

**Comment by ilqvya** [comment]
omg, Mac 13 is released, implement it natively plz

**Comment by effolkronium** [comment]
> * create new aggregate device

sorry, can you explain please how to do it with the Mac13 settings

**Comment by ilqvya** [comment]
> > * install [Background Music](https://github.com/kyleneideck/BackgroundMusic#recording-system-audio)
> > * set it as a microphone to Kap
> > * ✅ you are recording "internal sound"
> 
> Can confirm this works. Thanks @thearnica ! Didn't know about the Background Music app

Hey, I just found an easer way to record screen with all sounds 

-  install [Background Music](https://github.com/kyleneideck/BackgroundMusic#recording-system-audio)
-  Press **Command + Shift + 5**
-  Select "Background music" microphone in options

**Comment by timothyis** [comment]
There's no need to speak like that and be negative @effolkronium.

I appreciate that you edited your post, but your post is not helpful to this issue.

**Comment by eisenbruch** [comment]
Imagine thinking screen recording with Apple's built-in tool is superior to Kap

**Comment by ilqvya** [comment]
OBS program is able to capture screen audio without any crutches starting from macos 13

**Comment by timothyis** [comment]
Thanks for your input @effolkronium, but I'd like to reiterate that this thread is not a topic to share the benefits of other apps. This is counter-productive. I'm quite happy if you prefer using alternative software, but please stay on topic in this thread or don't take part.

**Comment by birobirobiro** [comment]
any update or alternative?

**Comment by Mennaruuk** [comment]
I've read that a program called [Audio Hijack](https://rogueamoeba.com/audiohijack/) can also record all internal audio. Does anyone know how they've managed to make this happen, and whether this could be somehow replicated within Kap?

**Comment by tibotiber** [comment]
I've just set it up in 10 minutes based on previous messages. I'm on Apple Silicon, not supported by Soundflower yet, but supported by BlackHole, which seems to be a modern equivalent, allowing to route audio between app, or in our case, create an aggregate mic that includes mic + system audio.

Here are the step:

1. Download and install BlackHole 2ch from https://existential.audio/blackhole/ (free or donate what you want)
2. Follow https://github.com/ExistentialAudio/BlackHole/wiki/Aggregate-Device
3. Select your desired mic and audio output (e.g. Mac Microphone and Mac Speakers) + BackHole 2ch
4. Name the aggregate audio device
5. Use it as microphone in Kap

ProTip: I'm using [Krisp](https://krisp.ai/) for noise cancelling on my microphone, it's cleaner to record and you can create your aggregate device using Krisp mic + Krisp speakers + BlackHole 2ch. Then dynamically pick the actual mic/speakers you want from Krisp when you record.

I hope it helps.

Thanks @leafac and @devnoname120! ✌️

**Comment by reisepass** [comment]
Good stuff 

I found this guy https://www.youtube.com/watch?v=YVRijTXsyA4   goes into more detail on configuring blackhole  about versus the link https://github.com/ExistentialAudio/BlackHole/wiki/Aggregate-Device   above 

I needed to do the extra step of creating a multi output device 

<img width="798" alt="Image" src="https://github.com/user-attachments/assets/18672dac-6f29-4efe-a468-ddef5ea7f08d" />

in addition to the aggregate device 

<img width="795" alt="Image" src="https://github.com/user-attachments/assets/2c641c89-52ec-4c62-a6a3-42b0dff4bc9e" />

not much to configure in blackhole 

<img width="790" alt="Image" src="https://github.com/user-attachments/assets/881e8dd2-61f3-4921-8481-8d6c9819af07" />

in system output choose multi output 

<img width="470" alt="Image" src="https://github.com/user-attachments/assets/3d570ea1-4d39-4a52-ab92-c578dbd067e8" />

in Kap  input settings choose aggregate device

<img width="556" alt="Image" src="https://github.com/user-attachments/assets/cb577a08-f07a-49cc-b38e-b089d56a162e" />
