### ISSUE TITLE
Getting error: `NonError: 1`

### ISSUE THREAD

**Issue by Overload119** [wulkano/kap#377]
```
NonError: 1
     at module.exports.input (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:14:10)
     at ShareService.showError (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:102:108)
     at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:151:17
     at Generator.throw (<anonymous>)
     at step (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:191)
     at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:402
     at <anonymous>
     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Comment by skllcrn** [comment]
We've been looking into this issue @Overload119, but have been struggling to reproduce it. We'll need some more details about your system and workflow; your OS version, the steps leading up to the error and anything else you think could be particular to your system. Does this by any chance happen when attempting to export a MP4 file? Does it occur consistently?

**Comment by randoum** [comment]
I experience this issue too, fresh install first time user on macOs Sierra 10.12.4

Here is what I've done:
- Disable mouse cursor recording, disable analytics
- record a part of the screen by dragging the dashed square
- After recording is done, it indicates the size 798*1278 
- Select 30 fps
- click MP4

Boom:
```
Error in plugin kap

NonError: 1
    at module.exports.input (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:14:10)
    at ShareService.showError (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:102:108)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:151:17
    at Generator.throw (<anonymous>)
    at step (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:191)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:402
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)
```

**Note**: saving other formats (Gif, WebM, APNG) works without complaining

**Comment by skllcrn** [comment]
Have you used Kap before @randoum? If you have, did you use any plugins?

**Comment by randoum** [comment]
As stated:
> I experience this issue too, **fresh install first time user** on macOs Sierra 10.12.4
First time I used Kap, the only thing i've done are listed in my previous message.

**Comment by matheuss** [comment]
https://github.com/wulkano/kap/pull/390 will help to figure out exactly what's going on here :) 🙏

**Comment by albinekb** [comment]
![image](https://user-images.githubusercontent.com/5027156/36643568-89bd8e06-1a4d-11e8-874e-df1b45f10e96.png)
I got the same error yesterday. It happened regardless if i made a new Kapture, changed resolution/FPS. 

Then I restarted Kap to see if that would fix it, and it did, so I didn't get any closer to narrowing it down. It's super weird. I have no idea where this is coming from? The only real difference when exporting MP4 compared to the other formats is this convert function: https://github.com/wulkano/kap/blob/master/app/src/scripts/convert.js#L73 so it feels like it must be something that goes wrong here?

**Comment by sonaro** [comment]
I was just able to reproduce this error on 2.0.0.681. OSX 10.13.3 High Sierra.

Error in plugin kap
NonError: 1
at module.exports.input (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:14:10)
at ShareService.showError (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:102:108)
at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:151:17
at Generator.throw ()
at step (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:191)
at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:402
at 
at process._tickDomainCallback (internal/process/next_tick.js:135:7)

skllcrn > @sonaro Looks like your issue is related to #377, does it happen consistently and only when exporting an MP4?

@skllcrn yes to both.  Custom size, 15 fps.  Exact same error every time.

**Comment by steveharman** [comment]
Let me know if I can help test anything.  This happens for me all the time when exporting MP4 - always has.   Yesterday, twice, I managed to export recordings as .MP4 but today it's back to situation normal.

**macOS 10.12.6**

NonError: 1
    at module.exports.input (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:14:10)
    at ShareService.showError (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:102:108)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:151:17
    at Generator.throw (<anonymous>)
    at step (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:191)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:402
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

I have not, to my knowledge installed any plugins - just installed Kap.

![editor](https://user-images.githubusercontent.com/12557929/36721860-ff54f33c-1ba3-11e8-9cdf-5bbcf1c978ba.png)

**Comment by karaggeorge** [comment]
After investigating for a whiiile, I managed to pinpoint what causes the error. Apparently, it's a problem with ffmpeg, and specifically the libx264 library it uses for h264 encoding. The problem is that the library requires both width and height to be divisible by 2. This is why it works half the times. If both your dimensions happen to be even, everything goes fine. If one of them is odd, it breaks. I am almost done writing the PR that fixes it.

**Comment by skllcrn** [comment]
Thank you so much @karaggeorge! For reference: https://www.quora.com/Is-it-true-that-H-264-MP4s-cannot-have-pixel-dimensions-that-end-in-odd-numbers-Why-is-this (via @sindresorhus)
