### ISSUE TITLE
running packaged app fails on a mac

### ISSUE THREAD

**Issue by hyalkaf** [wulkano/kap#38]
I want to start contributing to this project. I followed the instructions in the readme page. I packaged the app to try it out but it fails with this error: 

```
Uncaught Exception:
Error: Cannot find module 'electron-settings'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/hyalkaf/Desktop/My Files/Open Source/kap/dist/mac/Kap.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/hyalkaf/Desktop/My Files/Open Source/kap/dist/mac/Kap.app/Contents/Resources/app/dist/main.js:13:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

I already did npm install unless there are still some modules that need to be installed globally.

**Comment by CodeTheory** [comment]
Thanks for the report. We'll look into it.

**Comment by hyalkaf** [comment]
I can help debugging it too. doing npm start runs the app fine. I'm not sure where to start looking to debug the packaging of the app.

**Comment by matheuss** [comment]
Thank you for reporting, @hyalkaf! The last PR introduced a new `production` dependency in the `development` package.json – and I failed to review it correctly 😂
