### ISSUE TITLE
Disconnecting screen (DisplayPort/HDMI) causes crash

### ISSUE THREAD

**Issue by riderx** [wulkano/kap#414]
**Platform:** osx 10.13.4
**Kap Version:** 2.0.681
### Steps to reproduce
plug second screen in hdmi, start a record in kap, unplug , kap crash and you loose the whole record

**Comment by sindresorhus** [comment]
Does it display an error message? Or does it only silently quit?

**Comment by skllcrn** [comment]
I'm guessing the crash is caused due to the changing cropper/recording coordinates. Recreated with a display connected via Display Port:

```
Unhandled Promise Rejection
Error: Call `.startRecording()` first
    at Aperture.stopRecording (/Applications/Kap Beta.app/Contents/Resources/app.asar/node_modules/aperture/index.js:141:13)
    at EventEmitter.<anonymous> (file:///Applications/Kap%20Beta.app/Contents/Resources/app.asar/dist/renderer/js/main.js:195:39)
    at Generator.next (<anonymous>)
    at step (file:///Applications/Kap%20Beta.app/Contents/Resources/app.asar/dist/renderer/js/main.js:35:191)
    at file:///Applications/Kap%20Beta.app/Contents/Resources/app.asar/dist/renderer/js/main.js:35:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (file:///Applications/Kap%20Beta.app/Contents/Resources/app.asar/dist/renderer/js/main.js:35:99)
    at EventEmitter.stopRecording (file:///Applications/Kap%20Beta.app/Contents/Resources/app.asar/dist/renderer/js/main.js:207:20)
```
Kap doesn't crash but gives an error message when clicking the menubar icon to end the recording, you can however still access the main app window and continue using it.

**Comment by sindresorhus** [comment]
@riderx We have rewritten Kap to be more stable. Would you be able to try out [the beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.2) and see if you still can reproduce this issue?
