### ISSUE TITLE
Error when trying to save as mp4

### ISSUE THREAD

**Issue by swinggraphics** [wulkano/kap#416]
I have just installed Kap (downloaded app) and run it for the first time. I am able to save a recording in all formats except mp4. I'm happy to help troubleshoot any way I can.

**Platform:**
Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

**Kap Version:**
2.0.0.681

### Steps to reproduce
Make a recording; click export mp4; choose destination.

### Current behaviour
Error dialog:
Error in plugin kap
NonError: 1
    at module.exports.input (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:14:10)
    at ShareService.showError (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:102:108)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:151:17
    at Generator.throw (&lt;anonymous&gt;)
    at step (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:191)
    at /Applications/Kap.app/Contents/Resources/app.asar/dist/main/share-service.js:37:402
    at &lt;anonymous&gt;
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by swinggraphics** [comment]
Thanks!

**Comment by steveharman** [comment]
Looking good for me so far @sindresorhus (using Master).  No longer able to reproduce the crashing seen in 2.0.0 (Error in Plugin....)
