### ISSUE TITLE
Trying to get the cropping area to fullscreen resulsts in errors

### ISSUE THREAD

**Issue by NightMachinary** [wulkano/kap#442]
Platform: Darwin Fereidoons-MacBook-Pro.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
Step to reproduce :  1. Set the cropping area to the whole screen, in a fullscreen app. Move it a bit around, so that the cropping area's borders are off screen. 
Current behaviour: You'll get tons of errors like this:
```
Unhandled Error
RangeError: Maximum call stack size exceeded
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:1:1)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at BrowserWindow.cropperWindow.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:222:25)
    at EventEmitter._electron.ipcMain.on (/Applications/Kap.app/Contents/Resources/app.asar/dist/main/index.js:597:17)
```
And you need to do a pkill!
-->

**Kap Version:** Version 2.1.1 (2.1.1.747)

**Comment by sindresorhus** [comment]
I've seen this a lot on Sentry, but could not reproduce it. Thanks for the reproduction steps, @NightMachinary, that's very helpful.
