### ISSUE TITLE
Javascript error upon opening beta on 10.12.6 Sierra

### ISSUE THREAD

**Issue by freeassange** [wulkano/kap#558]
Hi I get this error when I try to open the program

A JavaScript error occurred in the main process

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/Users/xxxxx/Library/Application Support/Kap Beta/plugins/package.json'
    at Object.fs.openSync (fs.js:577:3)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.readFileSync (fs.js:483:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:563:29)
    at getExportOptions (/Applications/Kap Beta.app/Contents/Resources/app.asar/main/export-options.js:35:18)
    at Object.<anonymous> (/Applications/Kap Beta.app/Contents/Resources/app.asar/main/export-options.js:90:12)
    at Object.<anonymous> (/Applications/Kap Beta.app/Contents/Resources/app.asar/main/export-options.js:97:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

**Comment by sindresorhus** [comment]
Sorry for the trouble. This is a bug in the latest beta, occurring if you have not used Kap before.

A temporary fix is to download the [latest stable release of Kap](https://github.com/wulkano/kap/releases/tag/v2.2.0), run it once, delete it, and then download the [latest beta](https://github.com/wulkano/kap/releases/tag/v3.0.0-beta.2) and it should run successfully.

**Comment by mxstbr** [comment]
Just to note for repro reasons, I've used Kap before (and had it installed until I installed the beta) and this error still happens to me.

This fixed it for me:

```sh
cp -r ~/Library/Application Support/Kap/ ~/Library/Application Support/Kap Beta/
```
