### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by Justin-ZS** [wulkano/kap#669]
**macOS version:**
10.12.6

**Kap version:**
2.2.0.880

#### Steps to reproduce
After seeing this problem, I redownload and reinstall Kap. 
The latest version doesn't fix this issue.
Restart my mac can't change anything.
I'm sorry for unknown reproducible steps

#### Current behaviour
Unhandled Promise Rejection
Error: Call `.startRecording()` first
    at Aperture.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:141:13)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:207:39)
    at Generator.next (<anonymous>)
    at step (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:191)
    at file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:99)
    at EventEmitter.stopRecording (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:223:20)

**Comment by Justin-ZS** [comment]
**V3.0.0-beta.5** works fine!
