### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by benlumia007** [wulkano/kap#743]
I just installed using brew cask install kap or any other way, i keep getting 

Record Error
could not start recording within 5 seconds. 

then i get this

```
Unhandled Promise Rejection
Error: Call `.startRecording()` first
    at Aperture.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:141:13)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:207:39)
    at Generator.next (<anonymous>)
    at step (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:191)
    at file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:437
    at Promise (<anonymous>)
    at EventEmitter.<anonymous> (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:39:99)
    at EventEmitter.stopRecording (file:///Applications/Kap.app/Contents/Resources/app.asar/dist/renderer/js/main.js:223:20)
```

**Comment by StefanScherer** [comment]
I got it working. Catalina asked me to give Kap access to screen recording. I first clicked it away, then I had to look for it in the preferences -> Security & Privacy -> Screen Recording

<img width="780" alt="Screen Shot 2019-11-05 at 3 59 26 PM" src="https://user-images.githubusercontent.com/207759/68218826-40b97380-ffe5-11e9-9859-c130c50154eb.png">

**Comment by benlumia007** [comment]
then i don't know if its still a bug, but is it documented :D

**Comment by karaggeorge** [comment]
We're working on finding a way to check and point you to the settings when the permissions is not there, instead of failing silently 👍 

These permissions are new in Catalina, so there's not a lot of documentation around them yet
