### ISSUE TITLE
Error window, when I start recording 

### ISSUE THREAD

**Issue by fredsced** [wulkano/Kap#847]
Something went wrong while using the plugin “soundflower”
Error: Kap Output Device is not an input device
    at throwIfStderr (/Users/admin/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/index.js:22:11)
    at module.exports.<computed> (/Users/admin/Library/Application Support/Kap/plugins/node_modules/macos-audio-devices/index.js:11:12)
    at async Object.willStartRecording (/Users/admin/Library/Application Support/Kap/plugins/node_modules/kap-soundflower/index.js:97:3)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:44:7
    at async Promise.all (index 2)
    at async Object.startRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:136:3)

**Comment by skllcrn** [comment]
Thank you for the issue @fredsced, it would be great if you could submit it again in the plugin repository and include the details of your macOS and Kap version, and anything else that might help debug: https://github.com/karaggeorge/kap-soundflower
