### ISSUE TITLE
Kap shows error dialog and will freeze interaction to all windows

### ISSUE THREAD

**Issue by samundra** [wulkano/Kap#901]
**macOS version: ProductName: Mac OS X ProductVersion: 10.14.5 BuildVersion: 18F132**
**Kap version: 3.2.2**

#### Steps to reproduce
Downloaded and installed the latest version. Then after installing it, I tried to run it from menu bar as well. It errored out with dialog box as shown.

I had old version before and this is the screenshot from that version.
<img width="532" alt="Screen Shot 2020-07-22 at 02 38 08" src="https://user-images.githubusercontent.com/760855/88099749-cefe7580-cbc5-11ea-90c0-181a6095068d.png">

After that I downloaded new version and got the same kind of error.

![Screen Shot 2020-07-22 at 02 42 45](https://user-images.githubusercontent.com/760855/88099933-1553d480-cbc6-11ea-921b-d61f4b4c8ce7.png)

The only difference that I see in error dialog is "copy error" button next to Ok.

#### Current behaviour
Error dialog is shown as soon as Kap is run by clicking on menu bar icon. While this error dialog is open I can no longer interact with other windows. I then have to open terminal and kill Kap process to get back to normal state where I can interact with other window. It feels as if Kap is sitting on top of other windows and taking all mouse clicks. Because no matter where I click I hear error sound "ding" "ding" as I try to switch window by clicking on them.

#### Expected behaviour
Can use Kap without error.
#### Workaround
Have to open terminal manually using spotlight and then have to kill Kap process manually. I killed process using htop -> select Kap then kill it using SigKill.

#### More Info
I am using Yabai as my window manager.

**Comment by samundra** [comment]
I tried to run Kap from terminal and this is what I got back. I absolutely have no idea why I have this issue all of a sudden. Kap used to work fine as far as I can remember. This is the first time I have encountered this issue. 

```
➜  MacOS ./Kap
Error: schema is invalid: data.properties['password'].type should be equal to one of the allowed values, data.properties['password'].type should be array, data.properties['password'].type should match some schema in anyOf
    at CustomAjv.validateSchema (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:178:16)
    at CustomAjv._addSchema (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:307:10)
    at CustomAjv.compile (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:113:24)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/utils/plugin-config.js:35:29
    at Array.map (<anonymous>)
    at new PluginConfig (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/plugin-config.js:8:81)
    at new InstalledPlugin (/Applications/Kap.app/Contents/Resources/app.asar/main/plugin.js:48:21)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:228:46
    at Array.map (<anonymous>)
    at Plugins.getInstalled (/Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:228:34)
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: dialog module can only be used after app is ready
    at checkAppInitialized (electron/js2c/browser_init.js:803:11)
    at messageBox (electron/js2c/browser_init.js:892:3)
    at Object.showMessageBox (electron/js2c/browser_init.js:986:12)
    at showError (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/errors.js:18:35)
    at new InstalledPlugin (/Applications/Kap.app/Contents/Resources/app.asar/main/plugin.js:54:7)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:228:46
    at Array.map (<anonymous>)
    at Plugins.getInstalled (/Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:228:34)
    at Plugins.getRecordingPlugins (/Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:242:17)
    at Plugins.refreshRecordPluginServices (/Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:65:12)
Error: schema is invalid: data.properties['password'].type should be equal to one of the allowed values, data.properties['password'].type should be array, data.properties['password'].type should match some schema in anyOf
    at CustomAjv.validateSchema (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:178:16)
    at CustomAjv._addSchema (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:307:10)
    at CustomAjv.compile (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ajv/lib/ajv.js:113:24)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/utils/plugin-config.js:35:29
    at Array.map (<anonymous>)
    at new PluginConfig (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/plugin-config.js:8:81)
    at new InstalledPlugin (/Applications/Kap.app/Contents/Resources/app.asar/main/plugin.js:48:21)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:228:46
    at Array.map (<anonymous>)
    at Plugins.getInstalled (/Applications/Kap.app/Contents/Resources/app.asar/main/common/plugins.js:228:34)
```

Thanks in advance,
Samundra

**Comment by karaggeorge** [comment]
Hey, that is an issue with `kap-streamable`. We've opened and Issue and a PR over there: https://github.com/kevva/kap-streamable/pull/4, but we haven't heard anything.

To fix it, either delete your entire `~/Library/Application Support/Kap/plugins` directory, or if you don't want to have to install your plugins again, open `~/Library/Application Support/Kap/plugins/package.json` and remove `kap-streamable` from the dependencies
