### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by travisneedham** [wulkano/Kap#917]
**Sentry Issue:** [KAP-457](https://sentry.io/organizations/wulkano-l0/issues/1346275467/)

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.0

```
Unhandled Promise Rejection

TypeError: Error processing argument at index 0, conversion failure from 
    at setCropperShortcutAction (/Applications/Kap.app/Contents/Resources/app.asar/main/global-accelerators.js:24:24)
    at cleanup (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:77:3)
```

**Comment by karaggeorge** [comment]
Fixed in #916. Will be releasing a patch in a bit
