### ISSUE TITLE
Recording error

### ISSUE THREAD

**Issue by joshuanathanson** [wulkano/Kap#921]
**Sentry Issue:** [KAP-5VJ](https://sentry.io/organizations/wulkano-l0/issues/1560876167/)

**macOS version:**    Mojave (10.14)
**Kap version:**      3.3.1

```
Recording error

Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)
```

**Comment by mesqueeb** [comment]
I had it too today

**Comment by TristanBrotherton** [comment]
Me three. Reported via app.

**Comment by conceptblend** [comment]
Additional context for when this happened to me (and could repro). Kapturing another video of mine in Chrome with the contents zoomed in using the trackpad, not ⌘+ or ⌘-. Meta, right?!?

**Comment by skllcrn** [comment]
Changing the title of this issue to be a bit more specific, thank you for reporting!

**Comment by moulik-deepsource** [comment]
**MacOS Version : ** Catalina ( 10.15.7 )
**Kap Version : ** 3.3.2
```
Recording error

Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)
```
I am still getting this error.

**Comment by tpr-wtag** [comment]
I just got the issue today as well. recording started and automatically stopped within 2 second showing failure message.
Mac OS Big Sur
Version 11.0.1

**Comment by maxigimenez** [comment]
I'm getting the same error on `macOS Catalina 10.15.5`

```
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)
```

**Comment by ngeshlew** [comment]
Just from having the same issue just now on `macOS Big Sur`.

**Comment by gbcbooks** [comment]
i just have this issue too . 
Recording error
Error: Could not start recording within 5 seconds
at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:108:21)
This issue is already being tracked!

**Comment by mesqueeb** [comment]
got it again today

**Comment by VincentCATILLON** [comment]
Just to help about the root cause of this issue, it happens sometimes on my computer after multiple records (randomly) and i wasn't able to record again (even after reinstallation, temporary folders removed, etc), until i disabled microphone record 👍 

cc. @sindresorhus

**Comment by Pringels** [comment]
> I also hit this error today. It was when attempting to record from my second monitor which is a lower DPI. Moving the target and the recoding over to the retina laptop display seemed to get things going again.

I had the exact opposite this morning 😄  the retina display refused to start recording. Moving the target to my lower DPI display fixed the issue.

**Comment by dac09** [comment]
Confirming that this happens when using node-aperture 6.0.1, but not a problem on 5.2.0. Behaviour is inconsistent however, no problems on one machine, always fails with this error another.

**Comment by rafael-java** [comment]
Just had this problem :)

**Comment by billyct** [comment]
Just had this error

Kap 3.5.1
macOS 12.0.1 
Intel Core

it works well the first time, then always shows me `Error: Could not start recording within 5 seconds`.

Tested [aperture-node 6.1.0](https://github.com/wulkano/aperture-node) example code with the [electron-quick-start](https://github.com/electron/electron-quick-start), it also show me `Error: Could not start recording within 5 seconds`.

> Confirming that this happens when using aperture-node 6.0.1, but not a problem on 5.2.0. Behaviour is inconsistent however, no problems on one machine, always fails with this error on another.

it works well with [aperture-node 5.2.0](https://github.com/wulkano/aperture-node/tree/v5.2.0)

and when I test it in node, [aperture-node 6.1.0](https://github.com/wulkano/aperture-node) also can work well.

so maybe [aperture-node 6.x](https://github.com/wulkano/aperture-node) has some compatibility issues with [electron](https://github.com/electron/electron)?

**Comment by rm-rf-etc** [comment]
Experiencing this issue. Happens on both primary and external monitors. Worked the first time, then fails every time after.

Kap 3.5.1, installed using brew.

macOS Big Sur 11.6 (20G165)
MacBook Pro (16-inch, 2019)
2.4 GHz 8-Core Intel Core i9
32 GB 2667 MHz DDR4
AMD Radeon Pro 5300M 4 GB

**Comment by rafalbromirski** [comment]
Seems like it's an issue with 3.5.1 or even 3.5.0. I reinstalled older version (3.4.2) and everything is working fine

MacOS 12.0.1
MacBook Pro (13", 2017)

**Comment by hacke2** [comment]
Recording error
Error: Could not start recording within 5 seconds
    at Timeout._onTimeout (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/index.js:132:19)
MacOS 12.1

**Comment by levrik** [comment]
This issue was fixed in https://github.com/wulkano/aperture-node/pull/24 but Kap didn't update to [aperture-node 6.1.1](https://github.com/wulkano/aperture-node/releases/tag/v6.1.1) yet.

**Comment by willhindson** [comment]
Same error for me on 3.5.0/3.5.1— on latest OS version / Intel 2017 macbook pro 
Tried reinstalling 3.4.2 but that won't run at all. It only works on the first capture after a system restart.

**Comment by tmarshall** [comment]
started seeing this the other day.
MacOS 11.4
Kap 3.5.1
Intel macbook pro, 2019

going to update this machine's OS and see if it helps

**Comment by ron23** [comment]
Same issue here. on mac 11.6.2 (unknown Kap version, the about screen doesn't open up but I believe it should be the latest.)

**Comment by levrik** [comment]
@ron23 Try to open the about screen while having settings open. Then it pops up like expected.

**Comment by serg** [comment]
Perhaps it could be helpful for somebody.
There was this issue with Kap 3.5.0 and above.
Environment for testing: Big Sur 11.6.2 (CPU Intel).

As a workaround, the success solution is migration on [v3.4.2](https://github.com/wulkano/Kap/releases/download/v3.4.2/Kap-3.4.2.dmg) version of Kap. But before install, we need to completely remove previous version of Kap and all files related to this app. In this case would be helpful to use free app like AppCleaner (or other). Below is image about how it was look for tested environment above.
**IMPORTANT**: this view and list of files could be different on your side; use AppCleaner app with caution - only you are responsible for which files to remove.
![remove-kap-completely](https://user-images.githubusercontent.com/1274660/150584675-1b706cbd-a84c-4b26-9d33-7d2a585bd7f7.jpg)

**Comment by steakscience** [comment]
BTW, a restart fixes this

**Comment by BuffMcBigHuge** [comment]
> BTW, a restart fixes this

Not necessarily. I would have to reboot my intel-based Mac to get it working again. It works a single time before I experience the error and have to reboot again. Downgrading to v3.4.2 seems to have solved my issue for now.

**Comment by steakscience** [comment]
@BuffMcBigHuge Yup it broke again right after I posted the comment :(

**Comment by pvcresin** [comment]
The following steps solved it for me!
- AppCleaner -> Re-install Kap -> Reboot Mac(Intel)

**Comment by steakscience** [comment]
> The following steps solved it for me!
> 
> * AppCleaner -> Re-install Kap -> Reboot Mac(Intel)

From my experience and @BuffMcBigHuge 's, reboots only fixes it for 1 launch
