### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by datlass** [wulkano/Kap#922]
**Sentry Issue:** [KAP-5YD](https://sentry.io/organizations/wulkano-l0/issues/1573375782/)

**macOS version:**    Mojave (10.14)
**Kap version:**      3.3.1

```
Unhandled Promise Rejection

Error: EACCES: permission denied, mkdir '/Users/HomeFolder/.config/configstore'
You don't have access to this file.
    at make (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/configstore/node_modules/make-dir/index.js:61:12)
    at Function.module.exports.sync (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/configstore/node_modules/make-dir/index.js:84:9)
    at Configstore.set all [as all] (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/configstore/index.js:56:12)
    at new Configstore (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/configstore/index.js:25:13)
    at getConfigStore (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/first-run/index.js:18:9)
    at firstRun (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/first-run/index.js:22:22)
    at initializeAnalytics (/Applications/Kap.app/Contents/Resources/app.asar/main/common/analytics.js:23:7)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/index.js:88:3
```

**Comment by datlass** [comment]
Resolved by manually setting .config folder to read and write for staff and everyone.

**Comment by karaggeorge** [comment]
@sindresorhus looks like this came from `first-run`. Does it need that permission to work?

**Comment by sindresorhus** [comment]
@karaggeorge https://github.com/wulkano/Kap/issues/887#issuecomment-656576569
