### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by 99christina** [wulkano/Kap#923]
**Sentry Issue:** [KAP-5FX](https://sentry.io/organizations/wulkano-l0/issues/1520852224/)

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.1

```
Unhandled Promise Rejection

HttpError: 403 Forbidden
"<?xml version=/"1.0/" encoding=/"UTF-8/"?>/n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><X-Amz-Expires>300</X-Amz-Expires><Expires>2020-08-30T14:34:04Z</Expires><ServerTime>2020-08-30T15:43:52Z</ServerTime><RequestId>30D5583E1261F157</RequestId><HostId>cxLwd4H4c2EVhwEpPL5md9aYmgN5zmSWxaoQapB2bb2jU++volR3fHnTFuHn8sWqHAcotLVicBA=</HostId></Error>"
Headers: {
  "x-amz-request-id": "30D5583E1261F157",
  "x-amz-id-2": "cxLwd4H4c2EVhwEpPL5md9aYmgN5zmSWxaoQapB2bb2jU++volR3fHnTFuHn8sWqHAcotLVicBA=",
  "content-type": "application/xml",
  "transfer-encoding": "chunked",
  "date": "Sun, 30 Aug 2020 15:43:51 GMT",
  "server": "AmazonS3"
}
    at createHttpError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at IncomingMessage.<anonymous> (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:201:18)
```

**Comment by SgtPooki** [comment]
I wasn't even using the app at the time btw. it was just sitting in my menu bar.
