### ISSUE TITLE
Recording error

### ISSUE THREAD

**Issue by FengWu1206** [wulkano/Kap#936]
**Sentry Issue:** [KAP-623](https://sentry.io/organizations/wulkano-l0/issues/1599643755/)

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.2

```
Recording error

Error: Command failed: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/aperture/aperture {"destination":"file:///private/var/folders/95/02l5701136zg8lhxy2m21y4m0000gn/T/6250d4114facb1c658ee369f909e6398.mp4","framesPerSecond":30,"showCursor":true,"highlightClicks":false,"screenId":69679040,"cropRect":[[3,57],[1436,769]]}
Error Domain=AVFoundationErrorDomain Code=-11807 "Operation Stopped" UserInfo={AVErrorRecordingSuccessfullyFinishedKey=false, NSLocalizedDescription=Operation Stopped, NSLocalizedRecoverySuggestion=There is not enough available space to continue the file writing. Make room by deleting existing videos or photos., NSURL=file:///private/var/folders/95/02l5701136zg8lhxy2m21y4m0000gn/T/6250d4114facb1c658ee369f909e6398.mp4, NSUnderlyingError=0x7fc245f40050 {Error Domain=NSOSStatusErrorDomain Code=-67410 "(null)"}}
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:174:9)
    at /Applications/Kap.app/Contents/Resources/app.asar/node_modules/aperture/node_modules/execa/index.js:278:16
```

**Comment by sindresorhus** [comment]
I think the error message is pretty clear:

> There is not enough available space to continue the file writing. Make room by deleting existing videos or photos.

Although, we should present it better.

**Comment by MiaoChenhao** [comment]
Yes, this error occurs when you start recording!

**Comment by MiaoChenhao** [comment]
@karaggeorge Yes, this error occurs when you start recording!

**Comment by rafael-java** [comment]
I don't know if it's okay for me to be commenting on such an old issue, but I am getting it constantly nowadays... However, I am pointing the recording to an external drive with 9 GB of free storage. Indeed, my main drive is out of space, but I would think that this would not happen by pointing the recording to an external drive. And sometimes it does not happen... Well...
