### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by callzhang** [wulkano/Kap#950]
**Sentry Issue:** [KAP-68W](https://sentry.io/organizations/wulkano-l0/issues/1620049252/)

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.2

```
Unhandled Promise Rejection

Error: Command was killed with SIGSEGV (Segmentation fault): /Users/lei/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/key-cast -s normal -t 0.5 -d 415990306 -b {"bounds":[[0,0],[1600,1417]]}
    at makeError (/macos-key-cast/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/macos-key-cast/node_modules/execa/index.js:114:26)
    at async /Users/lei/Library/Application Support/Kap/plugins/node_modules/macos-key-cast/index.js:44:20
```

**Comment by ibearye** [comment]
Same error with me. the error has been fired a long time, why there are no any replies.
