### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by haroldpineda** [wulkano/Kap#957]
**Sentry Issue:** [KAP-7NK](https://sentry.io/organizations/wulkano-l0/issues/1849523128/)

**macOS version:**    Catalina (10.15)
**Kap version:**      3.3.2

```
Unhandled Promise Rejection

TypeError: Object has been destroyed
    at updateUi (/Applications/Kap.app/Contents/Resources/app.asar/main/dialog.js:49:24)
    at Object.action (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/errors.js:136:11)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/dialog.js:65:9
    at async IpcMainImpl.listener (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/electron-better-ipc/source/main.js:69:22)
```

**Comment by timothyis** [comment]
#1060 is a duplicate, however, has more activity and will track there.
