### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by carcagi** [wulkano/Kap#971]
**Sentry Issue:** [KAP-7SJ](https://sentry.io/organizations/wulkano-l0/issues/1858261186/)

**macOS version:**    High Sierra (10.13)
**Kap version:**      3.3.2

```
Error

Error: Command was killed with SIGABRT (Aborted): /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices list --input --json
dyld: Symbol not found: _$s18IntegerLiteralTypes013ExpressibleByaB0PTl
  Referenced from: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/node_modules/execa/index.js:114:26)
    at async Object.module.exports.<computed> [as getInputDevices] (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/index.js:10:20)
    at async getAudioDevices (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/devices.js:15:21)
    at async getMicrophoneItem (/Applications/Kap.app/Contents/Resources/app.asar/main/menus.js:114:19)
    at async getCogMenuTemplate (/Applications/Kap.app/Contents/Resources/app.asar/main/menus.js:161:3)
    at async Object.getCogMenu (/Applications/Kap.app/Contents/Resources/app.asar/main/menus.js:270:55)
```

**Comment by mihaicph** [comment]
I have same issue on 10.13.6 High Sierra.

**Comment by EnricoMonese** [comment]
Same error, High Sierra 10.13.6 (17G9016)



**Sentry Issue:** [KAP-7NG](https://sentry.io/organizations/wulkano-l0/issues/1849352311/)



**macOS version:**    High Sierra (10.13)
**Kap version:**      3.3.2

```
Error

Error: Command was killed with SIGABRT (Aborted): /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices list --input --json
dyld: Symbol not found: _$s18IntegerLiteralTypes013ExpressibleByaB0PTl
  Referenced from: /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices
  Expected in: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx/libswiftCore.dylib
 in /Applications/Kap.app/Contents/Resources/app.asar.unpacked/node_modules/macos-audio-devices/audio-devices
    at makeError (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/node_modules/execa/index.js:114:26)
    at async Object.module.exports.<computed> [as getInputDevices] (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/macos-audio-devices/index.js:10:20)
    at async getAudioDevices (/Applications/Kap.app/Contents/Resources/app.asar/main/utils/devices.js:15:21)
    at async /Applications/Kap.app/Contents/Resources/app.asar/main/common/settings.js:128:21
```

**Comment by karaggeorge** [comment]
This is definitely related to the swift tools not being bundled, since it's only happening on 10.13
I thought we handle this with returning an empty array.

I'll double check the backup is there, before we drop support for 10.13

https://github.com/wulkano/Kap/issues/838

**Comment by karaggeorge** [comment]
Looks like we do have the backup, but we still show the error dialog which I'm guessing is how this got reported, the app shouldn't have crashed or anything.

Maybe for future versions past 10.13 support we just silently return [], or we have some kind of warning the user that certain features won't work
