### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by riencoertjens** [wulkano/Kap#986]
**Sentry Issue:** [KAP-9ER](https://sentry.io/organizations/wulkano-l0/issues/2264324144/)

**macOS version:**    Big Sur (11)
**Kap version:**      3.3.2

```
Unhandled Promise Rejection

CancelError: Promise was canceled
    at PCancelable.cancel (/p-cancelable/index.js:99:17)
    at Object.didStopRecording (/kap-key-cast/index.js:54:17)
    at /Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:56:28
    at Array.map (<anonymous>)
    at callPlugins (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:53:66)
    at cleanup (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:74:9)
    at Tray.stopRecording (/Applications/Kap.app/Contents/Resources/app.asar/main/common/aperture.js:218:5)
```

**Comment by karaggeorge** [comment]
Moved this to the plugin repo as it's a plugin issue: 
https://github.com/karaggeorge/kap-key-cast/issues/7
